### ISSUE TITLE
Crashes When Asking for Call Details

### ISSUE THREAD

**Issue by muellert** [BelledonneCommunications/linphone-android#838] opened 2019-11-20 22:23 UTC
Hello! I just installed 4.2 beta from FDroid on my LineageOS 14 (Android 7.1.2), and when I see the list of previous calls and want to see the details of a specific call, I press the three dots on the right hand side of the call. In that case, Linphone crashes immediately.

**Comment by Viish** [comment] 2019-11-21 08:20
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/830

**Closed by Viish** 2019-11-21 08:20 UTC
