### ISSUE TITLE
linphone 6 - run in background but do not autostart & exit button

### ISSUE THREAD

**Issue by corobin** [BelledonneCommunications/linphone-android#2255] opened 2024-09-27 06:43 UTC
Howdy

1. **Describe the feature request** (mandatory)

this encompasses two related features.

a) on v5 there was a toggle for the background service and another toggle for auto start

b) on v5 there was an exit button right on the main left side menu. that has now been moved to hidden inside the help page on v6

the combined effect of these options was that it was possible to set linphone to NOT auto start - i.e. i will only launch it when I actually want it to be active - but once I have launched it, it will keep the service alive using the persistent notification until I exit the app via the exit button. This also means that easy access to the exit button is useful for actually exiting the app.

this configuration has applicable uses. for example, i don't want my phone to ring on incoming voip lines unless I am expecting something, then i will open the app, but once i do open it i do not want the app to stop functioning until i decide to exit it, because i am waiting for the expected call.

request: preserve the v5 behaviour on v6, namely:

a) have the background service / persistent notification be controlled separately from auto-start

b) have option to have exit button on main menu

3. **To Reproduce** (mandatory)

in advanced settings, enable "keep app alive using service"

in help, press exit

actual behaviour: the persistent notification will re-start itself after a moment

4. **Expected behavior** (mandatory)

once i exit the app the service should not auto start, until i re-open the app again

an exit button on the main menu

5. **Please complete the following information** (mandatory)

 - Device: OnePlus Nord N10 5G
 - OS: Android 11
 - Version of the App/SDK: see screenshot
 - Where you did got it from: Play Store
 - Please tell us if your Android is a Lineage OS or another variant: no

7. **Screenshots** (optionnal)

main menu, help circled in red. the exit button used to be at the bottom of this menu
![Screenshot_20240926-210036](https://github.com/user-attachments/assets/efd39547-8617-4f52-a5e0-3e22d9aaeba6)

version info
![Screenshot_20240926-210101](https://github.com/user-attachments/assets/3024f989-33f7-4249-8b6d-e8b721a13ae0)

**Comment by Viish** [comment] 2024-09-29 09:13
Hi @corobin,

I take note of your feedback.
The part that bugs me is: actual behaviour: the persistent notification will re-start itself after a moment

Once the app is killed, it shouldn't restart automatically except upon boot (and maybe if app is updated from the Play Store).
Could you attach logs showing the app starting by itself after being killed please?

Cheers,

**Comment by corobin** [comment] 2024-09-29 17:04
oh, i did take logs of that but didn't provide because i thought that was the intended behaviour, but if it's not supposed to restart after the app quits then the intended behaviour should be exactly what i am asking for. 

here you go: 

https://www.linphone.org:444//tmp/66f62d62157e0_316c8befedcb030623de.gz

https://www.linphone.org:444//tmp/66f62db4f0da7_8dbc16861d3899532006.gz

**Comment by Viish** [comment] 2024-09-30 09:26
Thanks.

I've made a fix for the quit() button not working as well as expected, but note that due to Crashlytics being enabled in the beta versions the app will auto restart due to it...
Crashlytics is disabled for the releases so it won't be a problem anymore when 6.0.0 will be released.

Cheers,

**Closed by Viish** 2024-09-30 09:26 UTC
Labels: status: feedback

**Comment by Viish** [comment] 2024-10-08 14:19
Hi @corobin,

FYI I've moved the quit button to the bottom of the drawer menu (only visible if keep alive service is enabled).

Cheers,

**Comment by azidman** [comment] 2024-12-30 15:01
Months later ... Still no autostart. :(

Samsung A40 + linphone-android-release-6.0.0-alpha.1512+942e78eed.apk

**Comment by 2dengine** [comment] 2025-01-09 18:20
I just tested version 6.0.0 on Android 11 and I can confirm that the app fails to auto-start. Another thing I noticed is that the dial screen is completely gone. Please bring back the dial screen with the large dial buttons!

**Comment by Viish** [comment] 2025-01-09 18:24
@2dengine dial pad still exists in start call view, click on icon next to filter text field.

**Comment by 2dengine** [comment] 2025-01-09 19:09
> @2dengine dial pad still exists in start call view, click on icon next to filter text field.

Thanks for the clarification. Easy access to the the dial pad is a must-have for older folks and people who use Linphone outdoors. The dial pad needs to be much larger and more prominent (preferably on the bottom row next to "Contact" and "Calls").

**Comment by corobin** [comment] 2025-01-09 19:14
@2dengine fwiw @Viish provided instructions to make the dial pad the default new call view in #2253

**Comment by 2dengine** [comment] 2025-01-10 09:32
> @2dengine fwiw @Viish provided instructions to make the dial pad the default new call view in #2253

Tried using the "remote provision" option but it had absolutely no effect.
I don't have the time to study and debug the app configuration.

**Comment by Viish** [comment] 2025-01-13 20:57
I added a floating action button to provider an easy way to show the dialpad in new call fragment.
