### ISSUE TITLE
pn-tok

### ISSUE THREAD

**Issue by arm-computech** [BelledonneCommunications/linphone-android#1438] opened 2021-07-01 12:03 UTC
How can you get the pn-tok variable into an asterisk?
Since when registering on Asterisk using sip, only the sip address and uuid are received in the header. And for push, I need the application token.

**Comment by Viish** [comment] 2021-07-01 12:25
Duplicate of https://github.com/BelledonneCommunications/linhome-android/issues/7

**Comment by Viish** [comment] 2021-07-01 12:29
To answer you I need more information.
What version of the app / SDK are you using? How did you configured it? etc...
Can you provide logs?

**Comment by arm-computech** [comment] 2021-07-01 12:54
I am using version 4.5.0. Downloaded from your repositories: https://linphone.org/releases/maven_repository/org/linphone/linphone-sdk-android/. Using the article I connected: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Android/.

But it also does not transfer pn-tok if you use the real version from the store.
For a month now I have not been able to solve the problem.

**Comment by arm-computech** [comment] 2021-07-01 13:00
Do you need to write something in the code, or should pn-tok fly by itself? And I also use the debug SDK version, do you need an implementation one?

**Comment by Viish** [comment] 2021-07-01 13:01
I recommend you take a look at our PushNotifications tutorial: https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/Pushnotifications
You can also take a look at this wiki page (push notification changes apply to 4.5 SDK release as well): https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Liblinphone%205.0%20new%20features%20and%20how%20to%20use%20them/#HPushnotifications

**Comment by arm-computech** [comment] 2021-07-01 14:18
Yes, no, everything is clear on push, it is not clear only why, when registering in sip, Asterisk does not receive pn-tok in the header. Since I read a lot in the articles, many have no problems with this, as if they get it automatically. And I get in Reg.Contact: sip: f0g1213123o2.vprib4@sip.linhome.org; gr = urn: uuid: fda15bc0-a74f-01ef-8fce-b72123ef65d. Here, all the more so here f0g1213123o2.vprib4@sip.linhome.org this address comes from somewhere.

**Comment by Viish** [comment] 2021-07-01 14:35
Push token is retrieved automatically from firebase if correctly configured (valid `google-services.json` file in app/ folder) and if you added the firebase dependencies & service in the Manifest.xml file:
```
dependencies {
  implementation 'com.google.firebase:firebase-messaging:19.0.1'
}
```
```
<service android:name="org.linphone.core.tools.firebase.FirebaseMessaging" android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
```

When it is retrieved, the push information is set in the CONTACT header of the next REGISTER as URI parameters, like this:
```
2021-07-01 16:31:53.801 30690-30690/org.linphone.debug I/belle-sip: channel [0x7c1e294d20]: message sent to [TLS://sip.linphone.org:5223], size: [1249] bytes
    REGISTER sip:sip.linphone.org SIP/2.0
    Via: SIP/2.0/TLS [2a01:e0a:278:9f60:8dc:43df:cf8f:b702]:41446;alias;branch=z9hG4bK.mBEBrI5XE;rport
    From: <sip:viish@sip.linphone.org>;tag=eFDzqzDjd
    To: sip:viish@sip.linphone.org
    CSeq: 22 REGISTER
    Call-ID: oaNFhs8Pms
    Max-Forwards: 70
    Supported: replaces, outbound, gruu
    Accept: application/sdp
    Accept: text/plain
    Accept: application/vnd.gsma.rcs-ft-http+xml
    Contact: <sip:viish@[2a01:e0a:278:9f60:8dc:43df:cf8f:b702]:41446;pn-provider=fcm;pn-param=929724111839;pn-prid=cOquHB-vQuufvmY4cuj6TT:APA91bFXfskuZsuL6_mAnQ8SXADK29AT27OonsS9V209o_8niRjupvW1KZz1XS8x_uJ6tfFfvYv8_MIvQBYHNqF7lvEwdXS6Iv_7zg8_i2zmASr3Hx1g30lebJ10rarh6wbglahZp2iQ;pn-timeout=0;pn-silent=1;transport=tls>;+sip.instance="<urn:uuid:832be5aa-1dad-00e6-aa1d-08362e57bb98>";+org.linphone.specs="ephemeral,groupchat/1.1,lime"
    Expires: 31536000
    User-Agent: Linphone/4.5.0-beta.75+78e66d4cf (Pixel 3a) LinphoneSDK/5.0.0-beta.5+b424c6d (release/5.0)
    Content-Length: 0
    Authorization:  Digest realm="sip.linphone.org", nonce="TFCI5AAAAADOLo/5AAAfBxzE+V8AAAAA", algorithm=MD5, opaque="+GNywA==", username="viish",  uri="sip:sip.linphone.org", response="be5e7e17ca4b938e3f12eaf8e2d34bb0", cnonce="DycF-MPUO6tWcIUj", nc=00000002, qop=auth
```
As you can see we now follow `RFC 8599` naming for parameters names, but if you need the "old way" (`pn-tok`, `app-id` and `pn-type` instead of `pn-provider`, `pn-param` and `pn-prid`) you can add the following in your linphonerc_factory file:
```
[net]
use_legacy_push_notification_params=1
```

**Closed by Viish** 2021-07-01 14:35 UTC

**Comment by arm-computech** [comment] 2021-07-02 06:03
I do everything according to the instructions, but for some reason I don’t get a token in the registration header of my Asterisk. Another question, does it depend on sdk? Or just the main one should be the google-services.json file, which is generated in Firebase and placed in the app folder. Of course, I also use the linhome application, maybe this application needs a specific sdk version, or do I need something, where can I change it?

**Comment by arm-computech** [comment] 2021-07-02 06:12
Can any specific settings be needed from Asterisk's side?

**Comment by arm-computech** [comment] 2021-07-02 06:19
When registering with Firebase, do you need to write org.linhome in the Android package name? What if I am using the linhome app? Just to clarify, there might be a problem here.

**Comment by Viish** [comment] 2021-07-02 07:26
> When registering with Firebase, do you need to write org.linhome in the Android package name?

That depends on the google-services.json you use. If you use your own, then your own package name should be inside this file and it must match the one you used for the app.

> Can any specific settings be needed from Asterisk's side?

I don't have any experience with Asterisk to help with that.

Also if you attach log I might be able to see what is going wrong.

**Comment by arm-computech** [comment] 2021-07-02 07:47
And I think the last question on the topic, I'll look further myself, maybe I'm doing something wrong. And you can write in which file the parameters are passed in the header for the client's vault when registering "using the vip". And How and where can this method be overridden? Well, for example, to forcibly transfer a token by generating it yourself. Of course, I will try to work out the option without affecting the VC registration code, but for the future.

**Comment by Viish** [comment] 2021-07-02 08:05
> And How and where can this method be overridden?

It's in the SDK so can't override it in your app, but you can fork the SDK to change how it's done.

**Comment by Viish** [comment] 2021-07-02 08:23
Or you can also disable the "auto push notification setup" feature in our SDK and do all the work by yourself in the app, like we did before 4.5 SDK release.

**Comment by arm-computech** [comment] 2021-07-09 09:59
Still, I could not get the token to my server in Asterisk. But the situation is this, I have an intercom, an Asterisk server and an application on my phone, all of them are on the same local network. If I block the Internet on the phone through the network gateway, leaving only the local network for the phone, and register with Asterisk, and then turn on the Internet on the phone, then it receives the token. How strange it is. Could you advise something, I don't know what to do.
