### ISSUE TITLE
Group Chat issue in Flexisip Server & Android Linphone APP

### ISSUE THREAD

**Issue by cat-2021** [BelledonneCommunications/linphone-android#1489] opened 2021-08-31 09:30 UTC
Hi,i hope you are fine ,can you help me about creating group chat using Flexisip Server with Android Linphone App.i also attached configuration of Conference Server kindly help me about this issue.

Thanks.

[conference-server]
enabled=true
transport=sip:127.0.0.1:6065;transport=tcp
conference-factory-uri=sip:conference-factory@sip.chatbubble.com
enable-one-to-one-chat-room=true
outbound-proxy=sip:127.0.0.1:5070;transport=tcp
database-backend=mysql
database-connection-string=db=flexisip user=flexisip password='flexisip' host=localhost
check-capabilities=true

[module::Registrar]
db-implementation=redis
redis-server-domain=localhost
redis-server-port=6379

**Comment by cat-2021** [comment] 2021-08-31 09:54
@Viish

**Comment by Viish** [comment] 2021-08-31 10:05
Duplicate of https://github.com/BelledonneCommunications/flexisip/issues/128

**Closed by Viish** 2021-08-31 10:05 UTC
