### ISSUE TITLE
Building linephone sdk for androidd app from scratch on linux system.

### ISSUE THREAD

**Issue by rksnachap333** [BelledonneCommunications/linphone-android#2157] opened 2024-05-01 08:44 UTC
Please suggest the steps to build sdk with g729 on linux system. That sdk i want to use in a android project.

**Comment by Viish** [comment] 2024-05-01 09:05
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/2155

**Closed by Viish** 2024-05-01 09:05 UTC
