### ISSUE TITLE
Crash when click on "recent" list calls

### ISSUE THREAD

**Issue by wkg** [BelledonneCommunications/linphone-android#1626] opened 2022-03-12 15:13 UTC
In "master" SDK and "master" android.

**Comment by Viish** [comment] 2022-03-12 21:23
Please attach logs from adb logcat, I dont reproduce.

**Comment by wkg** [comment] 2022-03-13 08:21
> Please attach logs from adb logcat, I dont reproduce.

Reproduced only in **incoming** recent calls...

[logcat.txt](https://github.com/BelledonneCommunications/linphone-android/files/8239161/logcat.txt)

**Comment by Viish** [comment] 2022-03-13 18:08
What do you mean by "incoming" recent calls? Call history view shows: all, missed and conferences.

Can you attach a non-obfuscated stack trace please?
And also SDK debug logs?

**Comment by wkg** [comment] 2022-03-13 18:19
> What do you mean by "incoming" recent calls? Call history view shows: all, missed and conferences.

In "all" history, but if call was outgoing - click work fine, if call was incoming - crash

> Can you attach a non-obfuscated stack trace please?
what does it mean? 

> And also SDK debug logs?
how?

i am attached video, maybe it help...

https://user-images.githubusercontent.com/1515379/158073479-6461b139-16e7-46b8-a184-9e16f35d187c.mp4

**Comment by Viish** [comment] 2022-03-13 18:31
> how?

Go to advanced settings, toggle on debug mode, restart app, reproduce the issue, go to advanced settings again and click on upload logs and finally copy/paste the link here please.

Thanks for the video, it helps even though I still can't reproduce it.

**Comment by wkg** [comment] 2022-03-13 18:45
> Thanks for the video, it helps even though I still can't reproduce it.

For me it reproduced on two devices.. I test "master" git version, in screenshot, in release versions it not reproduced...

> Go to advanced settings, toggle on debug mode, restart app, reproduce the issue, go to advanced settings again and click on upload logs and finally copy/paste the link here please.

what to put in url? i can't get logs.... second screenshot...
![Screenshot_20220313-214252](https://user-images.githubusercontent.com/1515379/158074456-d595f964-39d5-48e9-beaf-24b43eac28ac.png)
![Screenshot_20220313-214244](https://user-images.githubusercontent.com/1515379/158074458-7d3ba838-4f8c-4549-9b99-bb324aa54dd3.png)

**Comment by wkg** [comment] 2022-03-13 19:23
Maybe problem only in my build? Can you five me apk with git "master" ? or test my build...
https://fdroid.256.bz/org.linphone_40690.apk

**Comment by Viish** [comment] 2022-03-16 10:26
> For me it reproduced on two devices.. I test "master" git version, in screenshot, in release versions it not reproduced...

From your screenshot the app isn't master but 4.6.3. Only SDK is on master, which may not work properly with 4.6.3 app release.

> what to put in url?

`https://www.linphone.org:444/lft.php`

> Can you give me apk with git "master" ?

https://download.linphone.org/snapshots/android/linphone-android-debug-4.7.0-alpha.63+71a2140db.apk

**Comment by wkg** [comment] 2022-03-16 12:08
> `https://www.linphone.org:444/lft.php`

attach logs...
 
> https://download.linphone.org/snapshots/android/linphone-android-debug-4.7.0-alpha.63+71a2140db.apk

with this apk same problem...

[6231d27f89300_8fd6a983252fb44e759d.gz](https://github.com/BelledonneCommunications/linphone-android/files/8261910/6231d27f89300_8fd6a983252fb44e759d.gz)

**Comment by Viish** [comment] 2022-03-16 12:16
Thanks.
Can you attach stacktrace from adb logcat once more please? With debug apk it won't be obfuscated and thus more helpful.

**Comment by wkg** [comment] 2022-03-16 12:20
[6231d5e5a6c36_ecb37f522c118324a3ee.gz](https://github.com/BelledonneCommunications/linphone-android/files/8262019/6231d5e5a6c36_ecb37f522c118324a3ee.gz)
[logcat.txt](https://github.com/BelledonneCommunications/linphone-android/files/8262020/logcat.txt)

**Comment by wkg** [comment] 2022-03-16 12:23
Delete please my files, there is my contacts in... or say when i can delete...

**Comment by Viish** [comment] 2022-03-16 12:47
You can delete the log files if you want, I have them, thanks.

**Comment by Viish** [comment] 2022-03-16 13:25
Your issue should now be fixed by commit 13878ee4 in master branch.

**Closed by Viish** 2022-03-16 13:25 UTC

**Comment by wkg** [comment] 2022-03-16 16:11
Yes. It fix issue. Thank you!

> Your issue should now be fixed by commit [13878ee](https://github.com/BelledonneCommunications/linphone-android/commit/13878ee48dd82a5f8b1bc889a233fe74ff145738) in master branch.

Yes. It fix issue. Thank you!
