### ISSUE TITLE
"User Not Found" error in Linphone

### ISSUE THREAD

**Issue by Pamela-UK** [BelledonneCommunications/linphone-android#1042] opened 2020-06-05 01:58 UTC
I am testing a locally hosted Isabbel on a virtual machine. I created 2 extensions and installed Linphone on 2 Android mobiles. I was able to successfully register with server, but while dialing a extension (1001) it displays "**User not found**" message and does not connect in Linphone. 

I tried using other softphones like Zoiper, Skysip etc and all of them were working fine. Is it some sort of Bug in Linphone??? Or is it due to some configuration issues?? Please help.

**Comment by Viish** [comment] 2020-06-05 07:42
Please enable logs in advanced settings, restart the app, reproduce the issue and then upload logs using the send logs button in about page.

**Comment by Viish** [comment] 2020-07-06 07:20
No logs provided, closing.

**Closed by Viish** 2020-07-06 07:20 UTC

**Comment by WahidNasri** [comment] 2020-09-24 07:25
@Pamela-UK did you find the reason?
