### ISSUE TITLE
Liblinphone.so.10 is so big 

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1693] opened 2022-06-12 07:13 UTC
Hi Viish,

Hi,

After compiling linphone-desktop, liblinphone.so.10 is about 165M, why is it so big ? I compiled linphone-android before,
liblinphone.so is about 13M, How to reduce the size of liblinphone.so.10 generated by linphone-desktop?

thanks
Best regards.

**Comment by Viish** [comment] 2022-06-12 08:33
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/240

**Closed by Viish** 2022-06-12 08:33 UTC
