### ISSUE TITLE
Set local_preview_texture to invisible,incoming video call has no video in mobile network,but normal in wifi network

### ISSUE THREAD

**Issue by dante198406** [BelledonneCommunications/linphone-android#1903] opened 2023-04-13 09:30 UTC
Hi,
I set local_preview_texture to invisible,incoming video call has no video in mobile network,but normal in wifi network.
I don't need local preview,so I change it's visibility,then problem occurs as mentioned above.
I have tried  sdk from 2.3.5 to 5.+,all same results.
Why did this result occur？
Please help to check it,thanks,

Device: pixel 3
OS: Android 12

**Comment by Viish** [comment] 2023-04-13 12:12
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1898

**Closed by Viish** 2023-04-13 12:12 UTC

**Comment by Viish** [comment] 2023-04-13 12:14
If you still have the issue and need help, please continue the conversation on the original ticket, even if it is closed.

**Comment by dante198406** [comment] 2023-04-14 07:33
Sorry for that，I found it's not just a network issue,so strange，and I'll continue the conversation on #1898.
Tanks a lot
