### ISSUE TITLE
Multiple accounts:  no way to quickly chose from which account to make a call

### ISSUE THREAD

**Issue by axelsimon** [BelledonneCommunications/linphone-android#1500] opened 2021-09-09 16:21 UTC
**Describe the bug**
When you have multiple accounts configured, there is no quick and easy way to chose from which account to make a call.

You have to go into an account, toggle the "default account" setting on, and then make your call. If you want to make a call from a different account, you have to do that again for this second account, and every time you want to call from a different account. This quickly becomes tiresome and annoying :)

**Expected behaviour**
There should be a way to easily chose from which account to make a call. Ideally, an option to ask the question before every call, so that those who wish to be asked can be asked and those who always make calls from the same default account don't.
An inferior solution (in my opinion) would be a quicker way to make an account the default account. But that is easing the symptom rather than treating the real UX issue i think.

**Please complete the following information**
 - Device: probably not relevant, Pixel 2
 - OS: Android 11 (GrapheneOS)
 - Version of the App: 4.5.2
 - Version of the SDK: 5.0.15

**Comment by Viish** [comment] 2021-09-10 08:20
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1218

**Closed by Viish** 2021-09-10 08:20 UTC

**Comment by axelsimon** [comment] 2021-09-10 09:58
I see how this is a duplicate, however i think it would make more sense to track each improvement in a different issue, to be able to close them as the improvements are done.

However: your project, your call :smiley_cat:

**Comment by Viish** [comment] 2021-09-10 10:05
Don't worry, this is the n°1 improvement request we receive ;-)
