### ISSUE TITLE
Query related to local video stream customisation

### ISSUE THREAD

**Issue by RonitEcosmobian** [BelledonneCommunications/linphone-android#2021] opened 2023-11-03 06:05 UTC
Hi

I want to provide customisation of the video stream to be previewed and send as the remote stream. Customisation is for adding effects like blur in the background like a portrait effect of camera to show an object or face and the background is blur.

I'm using the Linphone SDK V5.2.110. 

It's kind on an urgent basis, would highly appreciate your quick reply.

Thanks

**Comment by Viish** [comment] 2023-11-03 09:27
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/352

**Closed by Viish** 2023-11-03 09:27 UTC
