### ISSUE TITLE
How does linphone-sdk support SIP BFCP?

### ISSUE THREAD

**Issue by leokwu** [BelledonneCommunications/linphone-android#1261] opened 2021-01-04 08:12 UTC
Hi，developers:

Could you please tell me how to support SIP BFCP in LINphone-SDK for dual-stream transmission?

thanks a lot.

**Comment by Viish** [comment] 2021-01-04 08:23
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/100

**Closed by Viish** 2021-01-04 08:23 UTC
