### ISSUE TITLE
On Android 6 H264 MediaCodecEncoder: could not configure encoder

### ISSUE THREAD

**Issue by xiaokuang95** [BelledonneCommunications/linphone-android#2078] opened 2024-01-12 02:56 UTC
Hello

I used it on an Android 6 device and found that the H264 encoder and decoder cannot be properly initialized. The device models are `{'MH ',' S3711 ',' mt6737m '} `Here is the log information
 [log](https://github.com/xiaokuang95/public/blob/main/sdk.log)

**Comment by xiaokuang95** [comment] 2024-01-12 03:00
Can I use soft coding? What should I do? SDK version 5.2.112

**Comment by Viish** [comment] 2024-01-12 07:57
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/2077, I already given you the link to the documentation on how to use OpenH264.

**Closed by Viish** 2024-01-12 07:57 UTC
