### ISSUE TITLE
Set Speaker enabled programatically

### ISSUE THREAD

**Issue by hammamziadeh12** [BelledonneCommunications/linphone-android#1332] opened 2021-03-29 17:50 UTC
Hey,

I'm using Android Linphone SDK for my app but instead of sound coming out from ear speaker, I want it to come out of normal speaker. How can I enable speaker programatically?

**Comment by Viish** [comment] 2021-03-29 19:10
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1330

**Closed by Viish** 2021-03-29 19:10 UTC
