### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by lib/armeabi-v7a/libbctoolbox.so 

### ISSUE THREAD

**Issue by ax3726** [BelledonneCommunications/linphone-android#2278] opened 2024-11-12 07:49 UTC
After referencing "com.github.barteksc:android-pdf-viewer:3.2.0-beta.1" pdf in the project, linphone reports an abnormal crash, the following is the log, how do I solve it?

2024-11-12 15:45:55.282  5807-5807  FactoryImpl             com.xm.judge.helper                  W  Unable to load optional library ffmpeg-linphone: dlopen failed: library "libffmpeg-linphone.so" not found
--------- beginning of crash
2024-11-12 15:45:55.289  5807-5807  AndroidRuntime          com.xm.judge.helper                  D  Shutting down VM
2024-11-12 15:45:55.292  5807-5807  AndroidRuntime          com.xm.judge.helper                  E  FATAL EXCEPTION: main
                                                                                                    Process: com.xm.judge.helper, PID: 5807
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~dHbj-HfoC7n9C-YCvozShw==/com.xm.judge.helper-TjQxkMOjAh3CK2cI49d9eA==/base.apk!/lib/armeabi-v7a/libbctoolbox.so"...
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1664)
                                                                                                    	at org.linphone.core.FactoryImpl.<clinit>(Factory.java:787)
                                                                                                    	at org.linphone.core.Factory.instance(Factory.java:49)
                                                                                                    	at org.linphone.LinphoneContext.<init>(LinphoneContext.java:108)
                                                                                                    	at org.linphone.helper.LinphoneHelper.init(LinphoneHelper.kt:37)
                                                                                                    	at com.xm.control.application.ClientApp.onCreate(ClientApp.kt:57)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2024-11-12 15:45:55.346  5807-5807  Process                 com.xm.judge.helper                  I  Sending signal. PID: 5807 SIG: 9

**Comment by Viish** [comment] 2024-11-13 10:35
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/443

**Closed by Viish** 2024-11-13 10:35 UTC
