### ISSUE TITLE
Receive and send audio and video packets

### ISSUE THREAD

**Issue by Berlin-Lu** [BelledonneCommunications/linphone-android#1771] opened 2022-09-21 01:32 UTC
May I ask how to operate it? I have checked the Linphone document, but I don't see it

**Comment by Viish** [comment] 2022-09-21 11:14
Sorry but that is way out of scope of the help I give on github.
Please contact our company for paid support: https://linphone.org/contact

Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1766

**Closed by Viish** 2022-09-21 11:14 UTC
