### ISSUE TITLE
MESSAGE notification does not persist

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1469] opened 2021-08-09 17:56 UTC
Using 80fa401d5 - (tag: 4.6.0-alpha) with SDK 5.0.1-pre.6+0253a33, frequently when I get a SIP `MESSAGE` there is no corresponding notification for it in the notification bar.  I only notice that I even have a message because I open the app and see the counter to the top right of the messaging pane button the bottom right linphone navigation bar.

But to be honest, this doesn't happen 100% of the time.  Sometimes I do see the notification for a `MESSAGE`.  Indeed, I suspect the notification is there for a (short?) period of time and then goes away without any interaction from the user.  It's almost like there is some kind of *timeout* on the notification where it only stays posted for some short-ish amount of time and then auto-disappears.

**Comment by Viish** [comment] 2021-08-23 10:54
Please app & SDK and if issue persists, attach logs.

**Comment by brianjmurrell** [comment] 2021-08-24 11:23
> Please app & SDK and if issue persists,

App and SDK version are in the first comment.

> attach logs.

[Here](http://brian.interlinx.bc.ca/linphone-notification-not-persistent.txt).  But to be honest, I didn't think this would be something that would show up in logs.

**Comment by Viish** [comment] 2021-08-24 11:27
>>  Please app & SDK and if issue persists,

> App and SDK version are in the first comment.

Sorry I forgot a word, it was meant to say "Please update app & SDK and if issue persists"

**Comment by Viish** [comment] 2021-08-24 11:30
Are you sure you didn't see any notification for this message?
Because in the logs it is sent to Android's notification manager and I don't see any log that would indicate we cancel that notification:
`2021-08-23 17:54:50:822 [org.linphone.debug/linphone-android] MESSAGE [Notifications Manager] Notifying 5`

**Comment by brianjmurrell** [comment] 2021-08-24 22:11
> Are you sure you didn't see any notification for this message?

Yes.  But as I said, I cannot be sure a notification was never posted and at some point removed (not be confused with being dismissed by the user -- I definitely did not dismiss the notification).  I didn't have my phone on and looking at it when the notification was raised.  I only noticed some time later when looking in the app that the number of unread msgs was > 0 and so opened them to see the unread msgs.

**Comment by Viish** [comment] 2021-08-25 11:17
I'm closing, if you reproduce with logs showing the issue I'll reopen.

**Closed by Viish** 2021-08-25 11:17 UTC

**Comment by brianjmurrell** [comment] 2021-08-25 13:31
> I'm closing, if you reproduce with logs showing the issue I'll reopen.

I'm not sure what you mean.  I provided logs of when it happened.  What is going to be different the next time?

**Comment by Viish** [comment] 2021-08-25 13:39
> What is going to be different the next time?

Maybe it will have a log that explain why the notification either didn't showed up or was removed, because in the log you provided there is nothing explaining the issue, so maybe there was no issue.

**Comment by Viish** [comment] 2021-08-28 09:04
I can't access the file, can you check?

**Comment by brianjmurrell** [comment] 2021-08-28 11:15
My apologies.  It's [here](http://brian.interlinx.bc.ca/linphone-didnt-post-notification2.txt).

**Comment by Viish** [comment] 2021-08-29 05:13
Not working either.

**Comment by brianjmurrell** [comment] 2021-08-29 15:09
Can you try again?  There might have been a DNS hiccup here.

**Comment by Viish** [comment] 2021-08-29 15:45
Ok this time I can access it, I'll take a look at it tomorrow.

**Comment by Viish** [comment] 2021-08-30 10:01
There's nothing in your log that would explain why the notif has disappeared, but it was displayed.
Can you check Android's notification settings for our app and ensure the chat message channel is enabled?

**Comment by brianjmurrell** [comment] 2021-08-30 12:28
All 4 channels are enabled.  Which makes sense, as I do some time see notifications from `MESSAGE`s.  Is only some of the time that they are not in the notification bar even though there are new/unread messages since I last looked.

**Comment by brianjmurrell** [comment] 2021-08-31 13:05
[Happened again](http://brian.interlinx.bc.ca/linphone-notification-not-persistent3.txt).  First a screenshot after the first `MESSAGE` came in:

![2021-08-31_08-57](https://user-images.githubusercontent.com/559317/131506441-59e87b82-bcf5-4c07-8848-9587ef07e628.png)

That notification persisted for a quite a while.  As you can see (in the log) a number of `MESSAGE`s were sent subsequently and the notification continued to persist (even after the last `MESSAGE` and then all of a sudden, through no action by the user, the notification is gone:

![2021-08-31_08-54](https://user-images.githubusercontent.com/559317/131506200-b68d2fc2-c569-470b-a1ab-81a877816ee2.png)

FWIW, the notification icon to the right of the Linphone notification icon is Hangouts.  Hangouts is getting a copy of all of the `MESSAGE`s being sent to linphone.  As you can see, it is not having any persistence problems.

I'd even show you a screenshot of the messages list in linphone showing that there are 3 unread messages but when I try to screenshot that screen I get a toast message as well as a notification that says:

**Couldn't save screenshot
Taking screenshots isn't allowed by the app or your organization**

**Comment by Viish** [comment] 2021-08-31 13:12
Your log file ends at 2021-08-30 20:59:44:407 but the screenshot where the notification has disappeared is 2021-08-30 22:35:00:000.
Could you get me the logs for the missing timeframe?

**Comment by brianjmurrell** [comment] 2021-08-31 13:18
Ah yes.  Of course.  I have updated the attachment in my previous message.  It should have logs until 22:35:10:193.  I captured the logs right after the screenshot.

**Comment by Viish** [comment] 2021-08-31 13:22
Thanks, that helps.
Seems like linphone-android was stopped:
```
2021-08-30 22:34:14:554 [org.linphone.debug/linphone-android] MESSAGE =========================================
2021-08-30 22:34:14:555 [org.linphone.debug/linphone-android] MESSAGE ==== Previous exit reason information dump ====
2021-08-30 22:34:14:555 [org.linphone.debug/linphone-android] MESSAGE REASON=Other
2021-08-30 22:34:14:557 [org.linphone.debug/linphone-android] MESSAGE TIMESTAMP=30-08-2021 22:33:44
2021-08-30 22:34:14:557 [org.linphone.debug/linphone-android] MESSAGE DESCRIPTION=empty #17
2021-08-30 22:34:14:557 [org.linphone.debug/linphone-android] MESSAGE =========================================
2021-08-30 22:34:14:557 [org.linphone.debug/linphone-android] MESSAGE ==== Previous exit reason information dump ====
2021-08-30 22:34:14:557 [org.linphone.debug/linphone-android] MESSAGE REASON=Excessive resource usage
2021-08-30 22:34:14:558 [org.linphone.debug/linphone-android] MESSAGE TIMESTAMP=30-08-2021 21:48:59
2021-08-30 22:34:14:558 [org.linphone.debug/linphone-android] MESSAGE DESCRIPTION=excessive cpu 6750 during 300002 dur=6287011 limit=2
2021-08-30 22:34:14:558 [org.linphone.debug/linphone-android] MESSAGE =========================================
```
And when that happens, at the next start (push received, user action, etc...) notifications will be removed, hence your issue.

**Comment by brianjmurrell** [comment] 2021-08-31 13:27
> Seems like linphone-android was stopped:

Are you saying stopped by the user or killed by Android?

**Comment by brianjmurrell** [comment] 2021-08-31 13:56
Let's give a day or two to be sure but my quick test here (send `MESSAGE`, observe the notification is posted, quit linphone from menu, re-open linphone, observe notification is still posted) seems to indicate at least that if your theory above is correct, it seems to resolve the issue.

**Comment by brianjmurrell** [comment] 2021-08-31 19:53
Hrm.  Noticing in the notification, I am only seeing the last message rather than a stack of the unread messages.  That is, if 3 messages come in and I don't read any of them, I only see the last one, not (a preview of) all 3.  Am I mis-recalling that linphone was showing stacked notifications before the above change?  Or am I just confusing linphone's notifications with other apps which do stack them and show you a small summary of all messages unread?

**Comment by brianjmurrell** [comment] 2021-08-31 21:46
Also, what conditions should make the notification disappear (other than swiping it away on the notification pull-down)?  Should simply opening linphone (without reading the unread messages) make it disappear?  Or should the messages have to be read?

I had the former happen.  Notification disappeared but all that I had done was open the app.  The messages are still showing as unread in the open linphone.

**Comment by Viish** [comment] 2021-09-01 07:16
> Hrm. Noticing in the notification, I am only seeing the last message rather than a stack of the unread messages

Yes, that is also due to the fact the app stops/restarts between messages. Even if the previous notifications now stays, when it creates the new one it doesn't add the new message to the previous ones, it overrides it. I'll see what I can do but I'm not sure I'll be able to find a proper solution.

> Or should the messages have to be read?

Yes, notification only disappears when message is marked as read or if user swipes the notification away.

**Comment by Viish** [comment] 2021-09-01 10:03
> I'll see what I can do but I'm not sure I'll be able to find a proper solution.

Ok I have a proper solution, but that requires an SDK update.

**Comment by brianjmurrell** [comment] 2021-09-01 11:19
> Yes, notification only disappears when message is marked as read or if user swipes the notification away.

So that's not the behaviour I was seeing.  Is that fix included in your aforementioned proper fix?

**Comment by Viish** [comment] 2021-09-01 11:29
I don't think so as I don't reproduce it.
Please try my fix (SDK 5.1.0-alpha-43 / App 4.6.0-alpha-55) and attach new logs if issue persists.

**Comment by brianjmurrell** [comment] 2021-09-01 11:31
I can't use alphas.  I need this to be stable enough for daily driver.

Since this is a bugfix, is a backport to the 4.5.x SDK not warranted?

**Comment by Viish** [comment] 2021-09-01 11:34
No, fix won't be made to 4.5 SDK.
It may be done on 5.0 SDK but I don't think it will be as we don't make patch updates for new APIs.

**Comment by brianjmurrell** [comment] 2021-09-01 12:03
Ah, sorry.  Yes, I meant 5.0.x SDK.

**Comment by brianjmurrell** [comment] 2021-09-01 14:53
> > Yes, notification only disappears when message is marked as read or if user swipes the notification away.
> 
> So that's not the behaviour I was seeing. Is that fix included in your aforementioned proper fix?

And now I am seeing the opposite behaviour.  `MESSAGE` is sent.  Notification is shown in notification list.  I open linphone, but not the chat the message is in.  Notification is still showing.  Open the chat the new message is in (making it read) and the Notification is still showing in the Notification list.

The app icon on the home screen also shows a "notification dot".

I have to go to the Notification list and click "Mark as Read" to make the Notification and the dot go away.  Additionally, clicking "Mark as Read" in the Notification does not dismiss it.  I also have to swipe it away.  Is that expected?

**Comment by Viish** [comment] 2021-09-01 15:00
I don' t reproduce your issue, can you attach new logs please?

**Comment by Viish** [comment] 2021-09-01 15:28
By the way I've make simplifications on how markAsRead() and notifications are handled in master branch (ecc318d0841fa67edec172cd7554b583831c7b76)

**Comment by brianjmurrell** [comment] 2021-09-01 21:16
So now I am seeing multiple messages in the notification.  It was probably erroneous to call them stacked as to me "stacked" means one application notification that when you open it, you see multiple individually actionable notifications.  [Fair Email](https://play.google.com/store/apps/details?id=eu.faircode.email&hl=en_CA&gl=US) does this.

But yes, now I am seeing multiple messages in the same notification.  Is that because the app has not been killed during the time those multiple messages were received?  Hrm.  Quitting the app and opening it again doesn't change the multiple messages in the notification, so that doesn't seem to be the reason either.

**Comment by brianjmurrell** [comment] 2021-09-01 21:21
> I don' t reproduce your issue, can you attach new logs please?

[Logs](http://brian.interlinx.bc.ca/linphone-notification-not-cleared-on-read.txt).  This is again the case where I open linphone (but not from clicking on a notification -- open from an icon on the home screen) and go read messages but the notification does not get dismissed from the notification bar.

**Comment by brianjmurrell** [comment] 2021-09-01 22:02
> > So now I am seeing multiple messages in the notification.
> 
> Yes, I fixed the only one message issue.

But I have not rebuilt/installed anything new.  Still on the same build as I have been seeing all of the issues here with.

> Indeed we currently don't do that, but that would be great indeed. I'll check tomorrow.

Fair Email is FOSS if you want to see what they are doing.  It's pretty neat.

> Again I can't access it...

I have 4 successful fetches of that URl and one failed:

213.143.10.197 - - [01/Sep/2021:17:21:35 -0400] "GET /linphone-notification-not-cleared-on-read.txt) HTTP/1.1" 404 244

But notice that it has the trailing `)` on it.  The successful ones don't have the trailing `)`.  Not sure if the above is you or not though.

**Comment by Viish** [comment] 2021-09-02 11:27
Ok then unless I reproduce the issue I consider this as resolved.

**Comment by brianjmurrell** [comment] 2021-09-02 13:04
Are these not bugfixes that would be appropriate to backport to 5.0.x?

**Comment by Viish** [comment] 2021-09-02 13:48
No it's an android app issue that requires new APIs to be fixed,so I won't port the new APIs to 5.0.x and we haven't planned to release a 4.5.3 anyway, 4.6.0 should be released soon.

**Comment by brianjmurrell** [comment] 2021-09-02 14:26
So is the 5.1.x SDK *really* still alpha, or is it considered to be more stable than alpha typically can be considered.

**Comment by Viish** [comment] 2021-09-02 15:17
At the current time it is a real alpha, we are aware of a few crashes specifically on Android (that also exists in 5.0.x), plus we are adding complex new features.
Except from that our CI suite ensures we stay under 2 failed tests before we merge changes, and we add new tests everyday, so the features are safe.
