### ISSUE TITLE
How to specify the network interface used by SDP? 

### ISSUE THREAD

**Issue by onetrio** [BelledonneCommunications/linphone-android#1541] opened 2021-11-03 01:25 UTC
Hi，my Android device is connected to the wireless network and the wired network at the same time. When calling the device in the wired network, the IP in the SDP is the IP address of the wireless network.

Can I make it use the address of the wired network？How to do it？

Thanks!

```
INVITE sip:know_@192.168.31.240 SIP/2.0
Via: SIP/2.0/UDP 192.168.31.46:5060;branch=z9hG4bK.185fBlfQs;rport
From: "InsightGuard" <sip:com.knowin@192.168.31.46>;tag=wgP~Bfnkg
To: "01010102" <sip:know_@192.168.31.240>
CSeq: 20 INVITE
Call-ID: H-ZzarYpEZ
Max-Forwards: 70
Supported: replaces, outbound, gruu
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, PRACK, UPDATE
Content-Type: application/sdp
Content-Length: 790
Contact: <sip:192.168.31.46;transport=udp>;+sip.instance="<urn:uuid:0bc23f6f-e2df-0022-9291-8c6734fec414>"
User-Agent: Unknown
v=0
o=com.knowin 62 2070 IN IP4 10.10.4.199
s=Talk
c=IN IP4 10.10.4.199
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 7078 RTP/AVP 96 97 98 0 8 99 100 101
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 speex/16000
a=fmtp:97 vbr=on
a=rtpmap:98 speex/8000
a=fmtp:98 vbr=on
a=rtpmap:99 telephone-event/48000
a=rtpmap:100 telephone-event/16000
a=rtpmap:101 telephone-event/8000
a=rtcp-fb:* trr-int 5000
a=rtcp-fb:* ccm tmmbr
m=video 9078 RTP/AVP 96 97
a=rtpmap:96 VP8/90000
a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=42801F
a=rtcp-fb:* trr-int 5000
a=rtcp-fb:* ccm tmmbr
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 nack sli
a=rtcp-fb:96 ack rpsi
a=rtcp-fb:97 nack pli
a=rtcp-fb:96 ccm fir
a=rtcp-fb:97 ccm fir
```

**Comment by Viish** [comment] 2021-11-03 08:27
Duplicate of https://github.com/BelledonneCommunications/liblinphone/issues/194

**Closed by Viish** 2021-11-03 08:27 UTC
