### ISSUE TITLE
Improvement Ideas

### ISSUE THREAD

**Issue by PublicBenemy** [BelledonneCommunications/linphone-android#1218] opened 2020-11-05 10:36 UTC
Hi there,

is this also place to put thoughts and ideas? If not, please apologize. I would like to throw in some ideas here, which are mainly driven by the fact that I use the app with multiple SIP accounts.

Display name » 
I'm using Linphone with 6 SIP accounts, which works very well. When opening the burger menu on the top left, the accounts are listed. For some reason, only for the default account, the "display name" appears + the sip FQDN. For the other accounts, only the FQDN appears.

Using Sipgate, the account name is something like 1234567e0@sipgate.de. For my 6 accounts, I don't know from memory which is which.

So it would be awesome to have the option to show the display name instead of user and domain.

Choose account for outgoing call »
I understand that the setting "default account" defines which account is used for outgiong calls. Is it possible to add an option to ask for every outgoing call, which account to use?

Account name in caller list »
I understand that all calls, nevertheless for which account, are in the caller list. I cannot see for or from which of my 6 accounts a call was assigned to. Is it possible to also display which of the SIP account the call was assigned to?

Ring tone for each account »
I understand that there is a general setting for a ring tone for the whole app. Is it possible to define ring tones for each SIP account?

I like the linphone app very much – thanks for alle the efforts so far!

Kind regards,
Benjamin.

**Comment by jelle-eastground** [comment] 2020-11-05 14:17
I've been using Linphone since today, but I'm very happy with it so far. These extra features would be great. Especially the 'Choose account for outgoing call' would make Linphone better than most other (free) Android VoIP apps. Since I use multiple accounts with different outbound phone numbers, this feature is quite essential for me.

**Comment by olegchensky** [comment] 2020-11-25 12:37
+++

**Comment by illspirit** [comment] 2021-09-13 05:04
Please please add this @Viish

**Comment by NeuerUser** [comment] 2022-01-06 16:45
Choose account for outgoing call »
I understand that the setting "default account" defines which account is used for outgiong calls. Is it possible to add an option to ask for every outgoing call, which account to use?

I propose that it should be easier to change the "Default account". E.g. just clicking on the hamburger then select the account. That's it. For this you would need to move the account settings into a submenu.

This is a pretty important feature, as I need to do calls on different lines. To always go into the account setting to set the account as default, is pretty cumbersome.

Thanks in advance! And a happy new year!

Michael

**Comment by martusi61** [comment] 2022-04-21 01:22
I have installed Linphone on a smartphone with different SIP accounts and I will have to do it on other devices, it would be nice to be able to export and import the configuration to avoid reloading it every time.

**Comment by wtwangcb** [comment] 2022-07-24 00:29
Would you also consider adding an option to enable DTMF dial tone?
This feature was removed in 4.6 release

**Comment by wtwangcb** [comment] 2022-07-24 00:32
Automatic call recording not working on Android 8.0

**Comment by sancholito** [comment] 2022-08-19 12:41
I'm using Linphone on Smartphone and Linux and I really like the application. In the desktop version I can click at the SIP account top left in the window and choose which account to activate for outgoing calls. On the mobile device I have to disable the account which I don't want to use, so that there is only one account active. After the call I have to repeat the procedure, so that both accounts become active again to accept phone calls. This is very inconvenient. I have two accounts at the same provider, because I have two companies with a different phone number each. 

Thanks!
Michael

**Comment by Viish** [comment] 2022-08-19 12:58
Hi @sancholito,

You don't have to do that.
In your account settings you can simply check the "Use by default" checbox to switch the default account.
We know this isn't very user-friendly and we will be working on improving that for the new UI we have started designing.

Cheers,

**Comment by sancholito** [comment] 2022-08-19 13:16
Hi @Viish 

Thank you for your reply. 
I saw that, but I couldn't see any visual feedback, which account is the default. Now I can see that there is a line stating "standard account" under the specified account in the settings. But in the hamburger menu in the startup page it's always the same account which is red highlighted, despite the no difference, or do I miss something?

Thanks

**Comment by Viish** [comment] 2022-08-19 14:25
> Now I can see that there is a line stating "standard account" under the specified account in the settings.

Indeed.

> But in the hamburger menu in the startup page it's always the same account which is red highlighted, despite the no difference, or do I miss something?

It might simply be an UI bug. 
Try killing the app & restarting it to see if it fixes the issue.

**Comment by m-gardet** [comment] 2023-02-10 12:57
Hi,
I'm using Linphone on Linux, it works fine but I can't use the Android version because there is no option <<specify gateway IP / public IP>>. 
Would it be possible to also have this option in the smartphone version?
Thanks

![nat-firewal-settings](https://user-images.githubusercontent.com/15226585/218097826-96fc843b-fb9b-47ef-9848-76b17d16a697.png)

**Comment by audacity76** [comment] 2023-03-01 09:22
Any news / planning about the account switching feature?

**Comment by Viish** [comment] 2023-03-01 09:42
> Any news / planning about the account switching feature?

Major UI redesign will start in a few weeks, and we hope to release it before the end of the year.

**Comment by Viish** [comment] 2023-09-25 14:41
Hi,

Just to let you know, in 6.0 release that is currently under development, the following suggestions have been added:

- Display name for each account
- Account name in caller list
- Quick switch of default account (2 clicks)

However this release won't include the ring tone for each account.

Cheers,

**Comment by adatum** [comment] 2024-02-15 00:20
>  Just to let you know, in 6.0 release that is currently under development, the following suggestions have been added:
> 
>     Display name for each account
>     Account name in caller list
>     Quick switch of default account (2 clicks)
> 
> However this release won't include the ring tone for each account.

Seeing the development activity on Linphone made me want to try it out again on android and linux. The last time I tried it was on version 3.x and it wasn't suitable for my needs. Now it's looking more viable.

Currently v5.2.3 for android from f-droid does not have the features listed above for 6.0 release. Can't wait for these essential usability settings changes to go live. Thanks for keeping the project alive!

**Comment by corobin** [comment] 2024-03-12 00:39
I noticed a buggy behaviour when dealing with multiple accounts. Given #104 and this thread I think it's best to add it here.

Summary: when there is multiple SIP accounts, clicking to call back a number in the call history page will fail unless that entry was generated with the current default account.

Steps:
1. set up 2 SIP accounts and select Account 1 as default
2. from another phone, call Account 1 and Account 2. it doesn't matter if you answer
3. go to call history page
4. press the missed call/call history entry that corresponds to the call you just made to Account 1
5. actual behaviour: will start a call back
6. press the other missed call/call history entry, which corresponds to the call you just made to Account 2
7. actual behaviour: will open the call back screen but also pop up the error screen. the error says password for *Account 1* is incorrect and prompting you to re-enter password

expected behaviour: call back using Account 2

Related, but other issue: currently, it is not clear in the UI what SIP account/phone number is associated with what action/history/etc

Hopefully both these can be resolved after the planned UI improvements

**Comment by dan-mcdonald** [comment] 2024-03-13 12:40
As a comparison Android handles multiple calling options quite well. When there is only 1 active SIM, the phone always uses that one; the UI never gets in the way. When you have a second active SIM card the phone will start asking which SIM when the user initiates a call, and there is a way to tell it to remember which SIM to use by default because the popups get annoying after a while. There is a way to label each SIM. There are some mechanisms to override the default like maybe long tapping on a call action button which prompts you to pick which SIM to use for just this call.

(From an organizational perspective the original scope of the issue was supposed to be broad but all of us are clamoring for a single feature. Maybe the Github Projects feature might be helpful for managing all the requested changes.)

**Comment by Viish** [comment] 2024-03-13 13:02
Hi @corobin  & @dan-mcdonald,

Yes our current way of handling multi-accounts is tedious at best.

Don't worry, as I already said (somewhere on a github issue) we are working on a 6.0 release for all of our apps with a brand new UI developped in concert with UX experts to provide a way better experience.
In 6.0 you'll be able to switch account in two clicks, and you'll only see call history / chat messages for the currently selected account.
When you'll receive a call, it will be indicated which account is being called.
In addition to account display name, you'll also be able to set a different "account avatar" to help differentiate between accounts.

I'm quite certain that everyone will appreciate the new UI compared to the actual one :), and I'm quite eager to have it published :)

**Comment by hobbit378** [comment] 2024-05-23 01:42
> 
> Yes our current way of handling multi-accounts is tedious at best.
> 
> Don't worry, as I already said (somewhere on a github issue) we are working on a 6.0 release for all of our apps with a brand new UI developped 

@Viish: 
I am eagerly waiting for the v6 Linphone for Android release with the announced UI enhancements,  notably the fast account switching. 
 **Has there  been already any  fixed release date for an (Alpha-, Beta-, RC-) release version  set by now**? Thanks in advance for posting a pertinent status update! 😀

**Comment by Viish** [comment] 2024-05-23 06:49
Hi @hobbit378,

6.0 is scheduled to be released at the end of June, and a public beta should be available at the beginning/middle of June (it currently is in private alpha, we're waiting for some features to be added in our SDK so we can implement them in our apps).

Cheers,

**Comment by Viish** [comment] 2024-07-16 08:04
6.0.0 alpha is now available in master branch and brings multi accounts improvements.

**Closed by Viish** 2024-07-16 08:04 UTC
Labels: type: enhancement

**Comment by hobbit378** [comment] 2024-08-01 16:23
@Viish 
Are there any (snapshot, nightly etc pp) builds of 6.0.0 alpha/ beta/rc pp available for download anywhere.
Haven't found anything so far in Belledonne Snapshot directory  
 Would really like to test it without going through all the hazzle of setting up a build environment and compiling it myself...

**Comment by Viish** [comment] 2024-08-01 16:26
Hi @hobbit378,

The android snapshots directory has a nightly build of the 6.0 : https://download.linphone.org/snapshots/android/

Latest one at the moment: https://download.linphone.org/snapshots/android/linphone-android-debug-6.0.0-alpha.1202+8a410fc77.apk

Cheers,

**Comment by hobbit378** [comment] 2024-08-01 19:05
Wow! Thank's for the super swift reply
Cheers,
Matthias


Sylvain Berfini ***@***.***> schrieb am Do., 1. Aug. 2024,
18:26:
