### ISSUE TITLE
Black Screen on incoming calls in KNOX 3.8 on Android 12 (Samsung A33)

### ISSUE THREAD

**Issue by screenio5** [BelledonneCommunications/linphone-android#1705] opened 2022-06-19 22:16 UTC
**Describe the bug**
When screen is OFF and call is received, incoming ringtone is heard but screen remains black

**To Reproduce**

1. Install latest 4.7.0 ("linphone-android-release-4.7.0-alpha.231+622275812.apk" as of this writing)
2. Go into KNOX "Secure Folder" and add the app into KNOX
3. Add a SIP account and make sure it connects and works
4. Do NOT uninstall the app from outside KNOX as the app INSIDE KNOX will crash upon phone restart (see other crash bug I have reported). Note that you dont need to setup a SIP account in the outside KNOX app.
5. Restart phone and run app from INSIDE KNOX. It should work fine
6. Shut off the phone's screen by pressing the power button
7. Make a phone call from an other phone
8. Phone will ring but screen remains black (you are not able to answer the phone call)
9. If you hang up and IMMEDIATELY place a new call, the phone will ring again BUT this 2nd time the screen turns ON showing the incoming call

**Expected behavior**
Screen should always turn on when incoming calls received

**Please complete the following information**
 - Device: Samsung A33
 - OS: Android 12
 - Version of the App: 4.7
 - Version of the SDK: 5.2.0-alpha.195 (as reported on the "About" app dialog)

**SDK logs**
Will provide if requested

**Additional context**
1. This bug materializes ONLY when the app is used inside KNOX (and the SIP account exists in the KNOX app instance).
2. No Google account exists on the Samsung A33
3. A 3rd party SIP account is used (not a Belledonne SIP account)

**Comment by Viish** [comment] 2022-06-20 05:57
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1704

**Comment by Viish** [comment] 2022-06-20 05:59
Hi,
Please provide the logs.

**Comment by Viish** [comment] 2022-06-20 08:07
If background mode "fixes" it, it means it is simply a push notification issue.
Can you still provide logs with background mode disabled please?

**Comment by Viish** [comment] 2022-06-20 08:37
Yes turn on the debug logs setting, restart the app, reproduce the issue and then use send logs button.
You will be prompted to select a way to share the file but you can ignore that and simply paste the link from your clipboard here.

**Comment by screenio5** [comment] 2022-06-21 00:09
Turning on the "Background Mode" in the version "https://download.linphone.org/snapshots/android/linphone-android-release-4.7.0-alpha.231+622275812.apk" I was previously using was successful -as reported above- in turning the screen ON every time  I was receiving calls.

Upon your suggestion I uninstalled the previous version and installed the version you suggested in "App crashes upon start in KNOX 3.8 on Android 12 (Samsung A33) #1704": https://download.linphone.org/snapshots/android/linphone-android-debug-4.7.0-alpha.255+86cba063d.apk 

This version now fails to turn the screen ON when receiving calls regardless of setting the "Background Mode" to ON like previously!
The only trick I have found to make the screen turn ON when receiving a phone call is this:

1) place a phone call and wait until it rings on the recipient phone (the recipient's screen remains black and incoming rings is heard)
2) cancel the call from the caller's phone
3) place immediately a new call on the caller's phone. This time the recipient's screen turns on and incoming ring is heard

I have made relevant logs but I dont want to post the links in public as there are details of the SIP server. Please provide other means of sending them to you.

**Comment by Viish** [comment] 2022-06-21 05:15
You can send them to me at sylvain.berfini@belledonne-communications.com

**Comment by Viish** [comment] 2022-06-21 09:34
I see nothing wrong in your logs.

Can you explain how you install the app in KNOX on a samsung device please? 
I don't see any KNOX app on the Samsung device we have.

**Comment by Viish** [comment] 2022-06-21 09:39
Also, do you reproduce the issue with 4.6.10 release from the Play Store / F-Droid?

**Comment by screenio5** [comment] 2022-06-21 09:49
1) In order to activate KNOX you need to enable "secure folder" under "biometrics and security" (you must create a Samsung account for this)
2) Once "secure folder" has been created, go into it and select the "+" sign. "Add apps" appears. Select "linphone". Knox will now add Linphone IN the secure folder (now you will have 2 instances of Linphone: one OUTSIDE the secure folder and one IN the secure folder. Note that each instance has its own settings.)
3) You are allowed to UNINSTALL the original instance outside the secure folder. However, if you do, upon restart of the phone you will experience the crash of the instance inside the secure folder as reported in my other bug report

**Comment by screenio5** [comment] 2022-06-21 09:51
I dont know regarding the 4.6.10 release you mention. I will check and let you know

**Comment by screenio5** [comment] 2022-06-22 09:01
4.6.10 release from the Play Store / F-Droid also does NOT turn on the screen when receiving calls.
It seems to me that ONLY version "https://download.linphone.org/snapshots/android/linphone-android-release-4.7.0-alpha.231+622275812.apk" when turning on the "Background Mode" had an actual effect AND TURNED ON the screen.

You mentioned that this version was "for our internal use only". Anything special about it that indeed made the screen work?

**Comment by Viish** [comment] 2022-06-22 09:16
No, this version isn't specific (except being a manual build from me for one of my coworkers) and there hasn't been any changes regarding your issue before or after.

**Comment by Viish** [comment] 2022-06-22 09:40
You have to enable "show content" in KNOX "notifications & data" for incoming call screen to be displayed when screen is OFF.
There's nothing I can do about it.

**Closed by Viish** 2022-06-22 09:40 UTC

**Comment by screenio5** [comment] 2022-06-22 09:47
But I have "show content" in KNOX "notifications & data"  set to ON and also "Background mode" set to ON in Linphone and still screen remains OFF.

**Comment by Viish** [comment] 2022-06-22 09:49
Then it may also be a bug from your KNOX version / device firmware as I don't reproduce it.

**Comment by screenio5** [comment] 2022-06-22 09:52
Does yours turn on the screen when receiving a phone call?
I have several phones here and none works

**Comment by Viish** [comment] 2022-06-22 09:52
Note that you must have you secure folder unlocked for incoming call to be displayed, otherwise it simply turns the screen ON...

**Comment by screenio5** [comment] 2022-06-22 09:54
Secure folder is locked with a password in my phone. I dont mind having to type the password to answer the phone.
The problem is when the screen does not turn on, therefore you cant type anything

**Comment by screenio5** [comment] 2022-06-22 09:56
Update: interesting twist. I turned OFF "Background mode" and set to OFF  "show content" in KNOX "notifications & data".
I restarted the phone then turned both to ON. Restarted phone again. NOW IT WORKS. Incoming calls wake the screen. I dont understand this...

**Comment by screenio5** [comment] 2022-06-22 17:19
Question: since dropping the 1st call and immediately making a 2nd ALWAYS turns on the screen, could it be possible to code such solution and being able to turn it ON upon some kind of global setting? (like having an option in a menu).
I suppose all KNOX users who use Linphone (and who lock the secure folder with a PIN/password) will be experiencing the same issue.

**Comment by screenio5** [comment] 2022-06-22 20:30
When running in secure folder, the app is not accessible by only knowing the phone's password.
One must also know the secure folder pin/password in order to use the app along other important apps that I chose to "protect" in the secure folder environment. 
By the way, I tried Xiaomi's similar solution (they call it "Second Space"). It simply doesnt work. When the user is the 1st space incoming calls are totally ignored (as linphone exists in the 2nd space)

I would be more than grateful if you manage to work any solution!!!!

**Comment by Viish** [comment] 2022-06-23 09:06
Hi @screenio5,

I believe I found a solution. It now works all the time on my device.
If you want to try it, here's an APK: https://download.linphone.org/snapshots/android/linphone-android-releaseWithCrashlytics-4.7.0-alpha.267+16d747477.apk
Note that it still doesn't work with "background mode" setting enabled.

**Comment by Viish** [comment] 2022-06-23 14:22
Great! Thanks for taking time to test it.

Fix will be merged on master branch shortly (so tonight's nightly build will have the fix) and will be part of next release (4.7 or 5.0 I  don't know yet it's name) that is scheduled for end of August / start of September.

The workaround is to use the incoming call notification as foreground service notification (up until now we waited for the call to be accepted to start the service as foreground).

Cheers!

**Comment by screenio5** [comment] 2022-06-25 12:51
I have been testing endlessly on the A32 and A33. I leave them on purpose for long time periods in idle state on purpose and then I call them to see whether screen turns on always (battery settings for the app and the OS are set so that Android never puts itself and the app to sleep).
So far, there have been 2-3 times (out of circa 50 times) that both phones have failed to turn on their screens and a 2nd immediate call was needed in order to turn it on.
Is there anything additional that comes to your mind that would eliminate even those corner cases and would make it possible to reach a 100% success in the turning on the screen?

**Comment by Viish** [comment] 2022-06-25 14:26
I don't know. If you reproduce the issue, please attach app debug logs.

Background mode leaves a Service always running in foreground mode to prevent the app from being killed by Android OS, it's required when push notifications aren't available to ensure call/message will be received and notified to the user.

**Comment by screenio5** [comment] 2022-06-25 14:35
So, if I understand correctly, it doesn't hurt, create any issues nor conflict with anything else if I turn "background mode", correct?
( I am willing to use anything that can help the app be always responsive)

**Comment by Viish** [comment] 2022-06-25 14:50
In your case it will prevent incoming call to turn the screen on, that's why I said previously to disable it.

**Comment by screenio5** [comment] 2022-06-25 15:16
Yes, I remember you mentioning this.
I have tried setting it to ON and for whatever reason the screen still keeps turning on.
I suppose I must keep it OFF always, correct?

**Comment by Viish** [comment] 2022-06-25 15:23
If screens turns on even with background mode enabled then you can keep it (even if you don't need it it's better to disable it).
But in my tests it wasn't working well with KNoX and secure folder.

**Comment by screenio5** [comment] 2022-06-27 07:12
An other

**Comment by screenio5** [comment] 2022-06-27 07:28
In Android 11 I had no issues. The app was never disconnected from server when the phone was left untouched for several hours.
Will setting on "background mode" resolve the problem? (I will try of course like I said).
If it does -and I will have to set it to ON always- how will then the turning on of the screen be resolved since this setting conflicts with the new fix you provided?

**Comment by screenio5** [comment] 2022-06-29 17:50
Apologies for reminding my last answer above. Please, when you have the time, can you please provide an answer?

**Comment by Viish** [comment] 2022-06-29 17:54
Yes background mode should maintain the connection between linphone and your server.
I don't know however if it will interfere with screen wake up or not.

**Comment by screenio5** [comment] 2022-06-29 19:48
Thanks for your reply.
My tests so far show that when I set background mode to ON, the connectivity of the app remains with the server (thus the app is always available to answer) BUT the screen unfortunately does not turn on (if I hung up and place a second call immediately then the screen turns on).
So, I am back to square one unfortunately!
Is there any trick you can do for having both the the background mode to ON and turning on the screen?

**Comment by Viish** [comment] 2022-06-29 20:02
Sadly no, as it would require two services: one for keeping the app alive and another one to turn the screen on.

**Comment by screenio5** [comment] 2022-06-29 21:02
I suppose by saying "sadly" its the end of the game as this feature will never be implemented, correct?

**Comment by Viish** [comment] 2022-06-29 21:06
Yeah...

Last thing you could do is install a flexisip as push gateway so you would be able to use push notifications with your SIP provider.
Or re-build linphone-android with your server push configuration.
Or simply switch to sip.linphone.org accounts.
