### ISSUE TITLE
How to recover call history from extension on linphone android

### ISSUE THREAD

**Issue by hieujames** [BelledonneCommunications/linphone-android#1763] opened 2022-09-13 09:26 UTC
Application linphone when deleting the app and reinstalling the app. I have lost all previous call history. How can I get the previous call Logs

**Comment by Viish** [comment] 2022-09-13 09:39
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1735

**Closed by Viish** 2022-09-13 09:39 UTC
