### ISSUE TITLE
 Duplication of text messages

### ISSUE THREAD

**Issue by lolfinger** [BelledonneCommunications/linphone-android#107] opened 2017-08-23 20:52 UTC
Algorithm for error occurrence:
1-st device: chat--new chat--enter recipient id--write message-send dutton
2-nd device answer to this message
1-st device - 2 chat with same contact

**Comment by DatBewar** [comment] 2017-08-25 09:59
Hello,
I'm not able to reproduce this.

**Comment by lolfinger** [comment] 2017-08-25 11:50
recipient ID means recipient not from contact list

**Comment by astuter** [comment] 2017-09-05 06:44
I also have faced this issue many times. It seems Linphone creates separate ChatRooms for chat initiated via means of Contacts, call history or direct entry of chat window.

**Comment by lolfinger** [comment] 2017-10-03 16:25
any updates?
or this is not a bug?

**Comment by DatBewar** [comment] 2017-10-11 08:36
I can't reproduce,
if you can have better steps to reproduce post her.

**Comment by astuter** [comment] 2017-10-11 11:43
Hello @DatBewar,

Consider my SIP username is 1000 and I'm trying to chat with my friend who is 2000. Following are possible ways I can start chating with 2000. 

1) From call History screen, move to detail screen of 2000 and start chat by pressing chat icon from history detail.
2) I haven't done any chat with 2000 in past, thus there will be no log for 2000 in ChatList screen. Someday, 2000 sends me a message and I start chating with him by giving reply to his incoming message. 
3) From ChatList screen, I press + button to start chating with 2000 via selecting him contacts. 
4) If 2000 is stored in my contact list, I go to contact detail screen of 2000 and start chat by pressing chat icon from there. 

If we have started chat by multiple ways as mentioned in above (1) to (4) steps, we will have more than one entry log/chatroom of 2000 in chatList screen. There should be only 1 log/chatroom for same user ideally.

**Comment by DatBewar** [comment] 2017-10-12 13:47
I try multiple time but nothing, I can't reproduce this.

**Comment by lolfinger** [comment] 2017-10-17 16:52
I'll make a video in a while

**Comment by iqbeeg** [comment] 2018-05-31 19:58
still hasn't been fixed?

**Comment by iqbeeg** [comment] 2018-05-31 20:00
no fix for this yet?

**Closed** 2018-11-12 11:18 UTC
Labels: status: feedback

**Comment by AlessandroBagnoli** [comment] 2019-02-20 10:39
@Viish closed this issue on 12 Nov 2018, so I'm guessing the bug is fixed. My question is: which commit fixes the problem?

**Comment by Viish** [comment] 2019-02-20 10:42
Actually I close this issue because we never reproduced it and the thread was quite inactive.
Try with the feature/release-4.1 branch and if issue is still there re-open this ticket.

**Comment by AlessandroBagnoli** [comment] 2019-02-20 10:46
> Actually I close this issue because we never reproduced it and the thread was quite inactive.
> Try with the feature/release-4.1 branch and if issue is still there re-open this ticket.

I cannot try with that branch. I forked master branch on 28 november 2018 and did a lot of customizations (both C and Java side). Forking feature/release-4.1 and re-apply all my customizations will take a (very) big amount of time :(

**Comment by Viish** [comment] 2019-02-20 10:48
First you can try with an up-to-date version of liblinphone to see if you still have the issue, that should be less time consuming.

**Comment by AlessandroBagnoli** [comment] 2019-02-20 11:56
I've managed to try latest 4.1 version. The bug is still present. You can easily reproduce it with the steps reported by the original post:
Algorithm for error occurrence:
1-st device: chat--new chat--enter recipient id--write message-send dutton
2-nd device answer to this message
1-st device - 2 chat with same contact

**Comment by Viish** [comment] 2019-02-20 12:05
Are you using a sip.linphone.org account or another ? What exactly do you type as recipient id ?

**Comment by AlessandroBagnoli** [comment] 2019-02-20 14:13
> Are you using a sip.linphone.org account or another ? What exactly do you type as recipient id ?

No, i register to my asterisk server through sip account.

**Comment by Viish** [comment] 2019-02-20 14:16
The only reason I see this could happen is if the second device answers with a from that differs from the one you used to send the first message.
Please attach logs from liblinphone.

**Comment by AlessandroBagnoli** [comment] 2019-02-20 15:54
```
2019-02-20 16:40:15.136 19062-19062/com.itel.itelphone I/liblinphone: Core callbacks [0x8a5e26b8] registered on core [0x8a40da80]
2019-02-20 16:40:19.002 19062-19062/com.itel.itelphone I/liblinphone: Callbacks [0x8a5e26b8] unregistered on core [0x8a40da80]
2019-02-20 16:40:22.928 19062-19062/com.itel.itelphone I/liblinphone: Chat room [ConferenceId(IdentityAddress(sip:teleconsulto@MYHOSTNAME), local=IdentityAddress(sip:893@MYHOSTNAME))] state changed to: State::Instantiated
2019-02-20 16:40:22.929 19062-19062/com.itel.itelphone I/liblinphone: Linphone core [0x8a40da80] notified [chat_room_state_changed]
2019-02-20 16:40:22.930 19062-19062/com.itel.itelphone I/liblinphone: Chat room [ConferenceId(IdentityAddress(sip:teleconsulto@MYHOSTNAME), local=IdentityAddress(sip:893@MYHOSTNAME))] state changed to: State::Created
2019-02-20 16:40:22.930 19062-19062/com.itel.itelphone I/liblinphone: Linphone core [0x8a40da80] notified [chat_room_state_changed]
2019-02-20 16:40:22.931 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4e80c in MainDb::insertChatRoom.
2019-02-20 16:40:22.932 19062-19062/com.itel.itelphone I/liblinphone: Insert new chat room in database: ConferenceId(IdentityAddress(sip:teleconsulto@MYHOSTNAME), local=IdentityAddress(sip:893@MYHOSTNAME)).
2019-02-20 16:40:22.939 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4e80c in MainDb::insertChatRoom.
2019-02-20 16:40:23.056 19062-19062/com.itel.itelphone I/liblinphone: Start measurement of [Get unread chat messages: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@MYHOSTNAME).].
2019-02-20 16:40:23.056 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4c480 in MainDb::getUnreadChatMessages.
2019-02-20 16:40:23.058 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4c480 in MainDb::getUnreadChatMessages.
2019-02-20 16:40:23.058 19062-19062/com.itel.itelphone I/liblinphone: Duration of [Get unread chat messages: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@MYHOSTNAME).]: 2ms.
2019-02-20 16:40:23.059 19062-19062/com.itel.itelphone I/liblinphone: Start measurement of [Get unread chat messages count of: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@MYHOSTNAME).].
2019-02-20 16:40:23.059 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4c400 in MainDb::getUnreadChatMessageCount.
2019-02-20 16:40:23.060 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4c400 in MainDb::getUnreadChatMessageCount.
2019-02-20 16:40:23.060 19062-19062/com.itel.itelphone I/liblinphone: Duration of [Get unread chat messages count of: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@MYHOSTNAME).]: 1ms.
2019-02-20 16:40:23.064 19062-19062/com.itel.itelphone I/liblinphone: Start measurement of [Get history range of: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@MYHOSTNAME, begin=0, end=20).].
2019-02-20 16:40:23.064 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4c3b8 in MainDb::getHistoryRange.
2019-02-20 16:40:23.066 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4c3b8 in MainDb::getHistoryRange.
2019-02-20 16:40:23.066 19062-19062/com.itel.itelphone I/liblinphone: Duration of [Get history range of: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@MYHOSTNAME, begin=0, end=20).]: 2ms.
2019-02-20 16:40:41.504 19062-19062/com.itel.itelphone I/liblinphone: Skipping top route of initial route-set because same as request-uri
2019-02-20 16:40:41.507 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:40:41.591 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:40:41.596 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a77d3a0]
2019-02-20 16:40:41.653 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67cce0]
2019-02-20 16:40:41.653 19062-19062/com.itel.itelphone I/liblinphone: Destroying op [0x8c09b700] of type [SalOpMessage]
2019-02-20 16:40:42.812 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4e2f8 in MainDb::addEvent.
2019-02-20 16:40:42.822 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4e2f8 in MainDb::addEvent.
2019-02-20 16:40:42.841 19062-19062/com.itel.itelphone I/liblinphone: Skipping top route of initial route-set because same as request-uri
2019-02-20 16:40:42.845 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:40:42.847 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4e338 in MainDb::updateEvent.
2019-02-20 16:40:42.850 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4e338 in MainDb::updateEvent.
2019-02-20 16:40:42.863 19062-19062/com.itel.itelphone I/liblinphone: Chat message 0xa6691440: moving from State::Idle to State::InProgress
2019-02-20 16:40:43.190 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:40:43.194 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67cce0]
2019-02-20 16:40:43.199 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4edb0 in MainDb::getHistorySize.
2019-02-20 16:40:43.200 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4edb0 in MainDb::getHistorySize.
2019-02-20 16:40:43.260 19062-19062/com.itel.itelphone I/liblinphone: Chat message 0xa6691440: moving from State::InProgress to State::Delivered
2019-02-20 16:40:43.261 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f200 in MainDb::updateEvent.
2019-02-20 16:40:43.269 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4f200 in MainDb::updateEvent.
2019-02-20 16:40:43.282 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67c020]
2019-02-20 16:40:43.365 19062-19062/com.itel.itelphone I/liblinphone: Unable to find chat room in RAM: ConferenceId(IdentityAddress(sip:teleconsulto@MYHOSTNAME), local=IdentityAddress(sip:893@PUBLICIP)).
2019-02-20 16:40:43.365 19062-19062/com.itel.itelphone I/liblinphone: Unable to find chat room in RAM: ConferenceId(IdentityAddress(sip:teleconsulto@MYHOSTNAME), local=IdentityAddress(sip:893@PUBLICIP)).
2019-02-20 16:40:43.366 19062-19062/com.itel.itelphone I/liblinphone: Chat room [ConferenceId(IdentityAddress(sip:teleconsulto@MYHOSTNAME), local=IdentityAddress(sip:893@PUBLICIP))] state changed to: State::Instantiated
2019-02-20 16:40:43.366 19062-19062/com.itel.itelphone I/liblinphone: Linphone core [0x8a40da80] notified [chat_room_state_changed]
2019-02-20 16:40:43.366 19062-19062/com.itel.itelphone I/liblinphone: Chat room [ConferenceId(IdentityAddress(sip:teleconsulto@MYHOSTNAME), local=IdentityAddress(sip:893@PUBLICIP))] state changed to: State::Created
2019-02-20 16:40:43.367 19062-19062/com.itel.itelphone I/liblinphone: Linphone core [0x8a40da80] notified [chat_room_state_changed]
2019-02-20 16:40:43.367 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4ed24 in MainDb::insertChatRoom.
2019-02-20 16:40:43.368 19062-19062/com.itel.itelphone I/liblinphone: Insert new chat room in database: ConferenceId(IdentityAddress(sip:teleconsulto@MYHOSTNAME), local=IdentityAddress(sip:893@PUBLICIP)).
2019-02-20 16:40:43.371 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4ed24 in MainDb::insertChatRoom.
2019-02-20 16:40:43.387 19062-19062/com.itel.itelphone I/liblinphone: Content type is unknown (text/plain), don't try to decrypt it
2019-02-20 16:40:43.387 19062-19062/com.itel.itelphone I/liblinphone: Chat message 0x8a5f1200: moving from State::Idle to State::Delivered
2019-02-20 16:40:43.388 19062-19062/com.itel.itelphone I/liblinphone: Start measurement of [Find chat messages: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@PUBLICIP).].
2019-02-20 16:40:43.388 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4ebb0 in MainDb::findChatMessages.
2019-02-20 16:40:43.390 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4ebb0 in MainDb::findChatMessages.
2019-02-20 16:40:43.390 19062-19062/com.itel.itelphone I/liblinphone: Duration of [Find chat messages: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@PUBLICIP).]: 2ms.
2019-02-20 16:40:43.391 19062-19062/com.itel.itelphone I/liblinphone: Linphone core [0x8a40da80] notified [is_composing_received]
2019-02-20 16:40:43.392 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4eb08 in MainDb::addEvent.
2019-02-20 16:40:43.395 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4eb08 in MainDb::addEvent.
2019-02-20 16:40:43.408 19062-19062/com.itel.itelphone I/liblinphone: Linphone core [0x8a40da80] notified [message_received]
2019-02-20 16:40:43.413 19062-19062/com.itel.itelphone I/liblinphone: Skipping top route of initial route-set because same as request-uri
2019-02-20 16:40:43.416 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:40:43.420 19062-19062/com.itel.itelphone I/liblinphone: Destroying op [0x8c09bb80] of type [SalOpMessage]
2019-02-20 16:40:43.430 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67cf80]
2019-02-20 16:40:43.491 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:40:43.497 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67d1c0]
2019-02-20 16:40:43.574 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f22c in MainDb::getEventFromKey.
2019-02-20 16:40:43.577 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4f22c in MainDb::getEventFromKey.
2019-02-20 16:40:43.578 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f230 in MainDb::updateEvent.
2019-02-20 16:40:43.582 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4f230 in MainDb::updateEvent.
2019-02-20 16:40:43.593 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f1dc in MainDb::getEventFromKey.
2019-02-20 16:40:43.595 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4f1dc in MainDb::getEventFromKey.
2019-02-20 16:40:43.596 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f1e0 in MainDb::disableDeliveryNotificationRequired.
2019-02-20 16:40:43.597 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4f1e0 in MainDb::disableDeliveryNotificationRequired.
2019-02-20 16:40:43.605 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67cf80]
2019-02-20 16:40:43.605 19062-19062/com.itel.itelphone I/liblinphone: Destroying op [0x8669c180] of type [SalOpMessage]















2019-02-20 16:42:40.143 19062-19062/com.itel.itelphone I/liblinphone: Skipping top route of initial route-set because same as request-uri
2019-02-20 16:42:40.146 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:42:40.228 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:42:40.233 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67d040]
2019-02-20 16:42:40.293 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67d1c0]
2019-02-20 16:42:40.294 19062-19062/com.itel.itelphone I/liblinphone: Destroying op [0x8c09bb80] of type [SalOpMessage]
2019-02-20 16:42:43.091 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4e2f8 in MainDb::addEvent.
2019-02-20 16:42:43.100 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4e2f8 in MainDb::addEvent.
2019-02-20 16:42:43.122 19062-19062/com.itel.itelphone I/liblinphone: Skipping top route of initial route-set because same as request-uri
2019-02-20 16:42:43.125 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:42:43.127 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4e338 in MainDb::updateEvent.
2019-02-20 16:42:43.130 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4e338 in MainDb::updateEvent.
2019-02-20 16:42:43.138 19062-19062/com.itel.itelphone I/liblinphone: Chat message 0x8a5f10c0: moving from State::Idle to State::InProgress
2019-02-20 16:42:43.195 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:42:43.199 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67d1c0]
2019-02-20 16:42:43.205 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4edb0 in MainDb::getHistorySize.
2019-02-20 16:42:43.206 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4edb0 in MainDb::getHistorySize.
2019-02-20 16:42:43.250 19062-19062/com.itel.itelphone I/liblinphone: Chat message 0x8a5f10c0: moving from State::InProgress to State::Delivered
2019-02-20 16:42:43.250 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f200 in MainDb::updateEvent.
2019-02-20 16:42:43.253 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4f200 in MainDb::updateEvent.
2019-02-20 16:42:43.262 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x8a67d7c0]
2019-02-20 16:42:43.284 19062-19062/com.itel.itelphone I/liblinphone: Content type is unknown (text/plain), don't try to decrypt it
2019-02-20 16:42:43.285 19062-19062/com.itel.itelphone I/liblinphone: Chat message 0x8a5f1ac0: moving from State::Idle to State::Delivered
2019-02-20 16:42:43.285 19062-19062/com.itel.itelphone I/liblinphone: Start measurement of [Find chat messages: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@PUBLICIP).].
2019-02-20 16:42:43.285 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4ebb0 in MainDb::findChatMessages.
2019-02-20 16:42:43.287 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4ebb0 in MainDb::findChatMessages.
2019-02-20 16:42:43.287 19062-19062/com.itel.itelphone I/liblinphone: Duration of [Find chat messages: (peer=sip:teleconsulto@MYHOSTNAME, local=sip:893@PUBLICIP).]: 2ms.
2019-02-20 16:42:43.288 19062-19062/com.itel.itelphone I/liblinphone: Linphone core [0x8a40da80] notified [is_composing_received]
2019-02-20 16:42:43.288 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4eb08 in MainDb::addEvent.
2019-02-20 16:42:43.292 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4eb08 in MainDb::addEvent.
2019-02-20 16:42:43.300 19062-19062/com.itel.itelphone I/liblinphone: Linphone core [0x8a40da80] notified [message_received]
2019-02-20 16:42:43.304 19062-19062/com.itel.itelphone I/liblinphone: Skipping top route of initial route-set because same as request-uri
2019-02-20 16:42:43.306 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:42:43.309 19062-19062/com.itel.itelphone I/liblinphone: Destroying op [0x8c09bd00] of type [SalOpMessage]
2019-02-20 16:42:43.313 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x9b77de60]
2019-02-20 16:42:43.372 19062-19062/com.itel.itelphone I/liblinphone: linphone_core_find_auth_info(): returning auth info username=893, realm=asterisk
2019-02-20 16:42:43.376 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x9b77ea00]
2019-02-20 16:42:43.440 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f22c in MainDb::getEventFromKey.
2019-02-20 16:42:43.445 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4f22c in MainDb::getEventFromKey.
2019-02-20 16:42:43.445 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f230 in MainDb::updateEvent.
2019-02-20 16:42:43.448 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4f230 in MainDb::updateEvent.
2019-02-20 16:42:43.456 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f1dc in MainDb::getEventFromKey.
2019-02-20 16:42:43.458 19062-19062/com.itel.itelphone I/liblinphone: Rollback transaction 0xbec4f1dc in MainDb::getEventFromKey.
2019-02-20 16:42:43.459 19062-19062/com.itel.itelphone I/liblinphone: Start transaction 0xbec4f1e0 in MainDb::disableDeliveryNotificationRequired.
2019-02-20 16:42:43.461 19062-19062/com.itel.itelphone I/liblinphone: Commit transaction 0xbec4f1e0 in MainDb::disableDeliveryNotificationRequired.
2019-02-20 16:42:43.468 19062-19062/com.itel.itelphone I/liblinphone: Unhandled transaction terminated [0x9b77de60]
2019-02-20 16:42:43.469 19062-19062/com.itel.itelphone I/liblinphone: Destroying op [0x8669c480] of type [SalOpMessage]
```

Here we are.

MYHOSTNAME = the hostname of the server running asterisk
PUBLICIP = the public IP my phone running linphone is connected to.

**Comment by Viish** [comment] 2019-02-20 15:59
From the logs you sent this is expected. You send a message to 893@MYHOSTNAME but the answer is sent from 893@PUBLICIP. Can't do much in the app and the lib if the answer doesn't come from the same address.
Configure your other client to use 893@MYHOSTNAME and you won't have this issue anymore.

**Comment by AlessandroBagnoli** [comment] 2019-02-20 16:44
The other client (JsSIP) already use 893@HOSTNAME, that's the point. I think the problem is linphone side. I don't understand why it uses PUBLICIP instead of HOSTNAME for chat creation

**Comment by Viish** [comment] 2019-02-20 16:45
Since you didn't attach the SIP messages I can't tell you why.

**Comment by AlessandroBagnoli** [comment] 2019-02-20 17:04
2019-02-20 17:57:47.779 22775-22775/com.itel.itelphone I/belle-sip: channel [0x89403500]: message sent to [TLS://MYHOSTNAME:5061], size: [760] bytes
    MESSAGE sip:615@MYHOSTNAME SIP/2.0
    Via: SIP/2.0/TLS 192.168.5.126:38718;branch=z9hG4bK.dWPCc9Pr8;rport
    From: <sip:893@MYHOSTNAME>;tag=nyz8i8gf-
    To: sip:615@MYHOSTNAME
    CSeq: 21 MESSAGE
    Call-ID: xdafC9bRIi
    Max-Forwards: 70
    Supported: replaces, outbound, gruu
    Date: Wed, 20 Feb 2019 16:57:47 GMT
    Content-Type: text/plain
    Content-Length: 4
    X-EvenType: text
    X-Even: itelphone
    X-Caller: 893
    X-Callee: 615
    User-Agent: ITELphoneAndroid/4.0.1 (belle-sip/1.6.3)
    Authorization:  Digest realm="asterisk", nonce="1550681870/17d7648c22c72cf577ff4da921d91517", algorithm=md5, opaque="51a7a9ba76a8640c", username="893",  uri="sip:615@MYHOSTNAME", response="8689d10d6f936f03069dade4db92c4d3", cnonce="xilmiOS9Hcvcu50B", nc=00000001, qop=auth
    
    Ciao




2019-02-20 17:58:22.337 22775-22775/com.itel.itelphone I/belle-sip: channel [0x89403500]: received [487] new bytes from [TLS://MYHOSTNAME:5061]:
    MESSAGE sip:893@PUBLICIP:38718;transport=tls SIP/2.0
    Via: SIP/2.0/TLS MYHOSTNAMEPUBLICADDRESS:5061;rport;branch=z9hG4bKPj47cf5a88-4222-40e1-95d6-920bdde0330d;alias
    From: <sip:615@MYHOSTNAME>;tag=cbe8f591-7ae0-40d2-90f0-051e9904e3c4
    To: <sip:893@PUBBLICIP>
    Contact: <sip:893@MYHOSTNAMEPUBLICADDRESS:5061;transport=TLS>
    Call-ID: 29d9fede-07aa-40bc-8493-f3fdc7a5d886
    CSeq: 31733 MESSAGE
    Max-Forwards: 70
    User-Agent: Asterisk PBX 16.0.0
    Content-Type: text/plain
    Content-Length:     4
    
    ciao

**Comment by Viish** [comment] 2019-02-20 17:07
As you can see message that is sent from linphone (the first one) From and To headers are OK, but in what your server send for the second message the To header is wrong.
Check either your server config or the client that sends the second message (which isn't linphone obviously)

**Comment by AlessandroBagnoli** [comment] 2019-02-21 16:03
You are right, but it seems like liblinphone solves MYHOSTNAME to PUBLICIP when it receives the SIP Message...this does not make any sense.

**Comment by Viish** [comment] 2019-02-26 14:02
This is obviously a proxy issue. I'm not a freeswitch expert so I can't help you with that.
All that I can say is our client doesn't resolve domain names to IP upon receiving a message and using another server (flexisip) we don't reproduce this behavior.

**Comment by RajanVindaloo** [comment] 2019-09-03 04:37
Hello Viish, 
From the above message, you are saying that your developer has fixed this MYHOSTNAME or PUBLICIP from the FreeSWITCH side not in the linphone application.

**Comment by Viish** [comment] 2019-09-03 06:54
Hi Rajan,
Yes this is what I'm saying.
If the proxy sets your IP in the TO header of the message you will have multiple conversations, however if it uses the domain of your proxy it will be fine.

**Comment by RajanVindaloo** [comment] 2019-09-11 13:00
Hi Viish,
In older version of linphone, a developer can set sipuri while creating/sending a message. But, in the latest version, it's not possible to set it. Would you help me with that?

**Comment by Viish** [comment] 2019-09-11 13:18
@RajanVindaloo Please open a new ticket.

**Comment by RajanVindaloo** [comment] 2019-09-11 13:19
Okay. Thank you.
