### ISSUE TITLE
Call video shows green

### ISSUE THREAD

**Issue by fengfeilong0529** [BelledonneCommunications/linphone-android#1588] opened 2022-01-13 10:22 UTC
Hello, when I use linphone 4.4 & 4.2 aar to test the intercom, I found that the video will be displayed in green when there is a device intercom, please help me to see where the problem is? Are there parameters that can be set?
@Viish Help pls!

**Comment by fengfeilong0529** [comment] 2022-01-14 02:14
I found that it is normal to use VP8 format , but the actual use scene determines the H264 format

**Comment by Viish** [comment] 2022-01-14 09:16
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1153

**Closed by Viish** 2022-01-14 09:16 UTC
