### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by NilayPorwal** [BelledonneCommunications/linphone-android#636] opened 2019-05-18 11:15 UTC
java.lang.RuntimeException: Unable to start service org.linphone.LinphoneService@48232fe with Intent { cmp=packagename.debug/org.linphone.LinphoneService }: java.lang.RuntimeException: LinphoneService not instantiated yet

  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3738)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:7022)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
     Caused by: java.lang.RuntimeException: LinphoneService not instantiated yet
        at org.linphone.LinphoneService.instance(LinphoneService.java:291)
        at org.linphone.notifications.NotificationsManager.startForeground(NotificationsManager.java:225)
        at org.linphone.notifications.NotificationsManager.<init>(NotificationsManager.java:117)
        at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:196)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3707)
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:197) 
        at android.app.ActivityThread.main(ActivityThread.java:7022) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

**Comment by Viish** [comment] 2019-05-18 14:41
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/633

**Closed by Viish** 2019-05-18 14:41 UTC
