### ISSUE TITLE
Linphone not getting video

### ISSUE THREAD

**Issue by dabhi86** [BelledonneCommunications/linphone-android#2012] opened 2023-10-17 14:35 UTC
Hi Team Linphone,

I have a device with Windows 7 OS using OPAL Library and Codec - VP8, when I receive call from this device then Linphone SDK 5.3 shows "**No Video Input**" error. Interesting thing is that if I use Linphone SDK 4.5 then I get the video correctly but with latest Linphone Library, I am getting this problem.

Please help me fix this bug and **please leave the ticket open** as this issue is really important and I guess latest Linphone SDK has a bug which is causing this issue.

These are the Logs - https://www.dropbox.com/scl/fi/k2cumgdfsn3q3e4fj6sue/logs5.3.txt?rlkey=vkxy9tbjzkb7wbn8lbzh06t3i&dl=0

**Comment by Viish** [comment] 2023-10-18 09:42
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1992

**Closed by Viish** 2023-10-18 09:42 UTC
