### ISSUE TITLE
Incoming MESSAGEs are filed into different chats based on registered IP address

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#680] opened 2019-06-05 16:56 UTC
I have several chats from a single recipient with my SIP SIMPLE MESSAGEs to and from them scattered across the several chats.

It appears that to linphone, if the IP address of the recipient is different, because the IP address that was registered to was different (i.e. multi-homed proxy) then it files the message into a different chat.

For example, this message:

```
MESSAGE sip:my_sip_account@10.75.22.32:57832;transport=tcp;app-id=755770037818;pn-type=firebase;pn-timeout=0;pn-tok==[redacted];pn-silent=1 SIP/2.0
Via: SIP/2.0/TCP 10.75.22.8:5060;rport;branch=z9hG4bKPjda0a9dff-d56c-441f-b737-81d8cad9dc2a;alias
From: "5565551212" <sip:[redacted]@pbx.example.com>;tag=f1f9e034-2734-47ad-89d6-4316caaba8a5
To: <sip:my_sip_account@10.75.22.32;app-id=755770037818;pn-type=firebase;pn-timeout=0;pn-tok==[redacted];pn-silent=1>
Contact: <sip:my_sip_account@10.75.22.8:5060;transport=TCP>
Call-ID: 998d2f8c-ecd8-41c1-a063-865e2f2a149e
CSeq: 38811 MESSAGE
Max-Forwards: 70
User-Agent: Asterisk PBX 13.26.0
Content-Type: text/plain
Content-Length:    17

[redacted]
```

and this message:

```
MESSAGE sip:my_sip_account@10.75.22.32:57832;transport=tcp;app-id=755770037818;pn-type=firebase;pn-timeout=0;pn-tok==[redacted];pn-silent=1 SIP/2.0
Via: SIP/2.0/TCP 10.75.22.8:5060;rport;branch=z9hG4bKPj39b15fb0-305c-4b31-af19-cf2d1be40d7b;alias
From: "5565551212" <sip:[redacted]@pbx.example.com>;tag=0f7acbf8-c5fb-4a1b-96a3-e650a93c8553
To: <sip:my_sip_account@10.75.22.32;app-id=755770037818;pn-type=firebase;pn-timeout=0;pn-tok==[redacted];pn-silent=1>
Contact: <sip:my_sip_account@10.75.22.8:5060;transport=TCP>
Call-ID: 93fbf102-79c4-406d-933a-8d5bc0e1fd4f
CSeq: 35306 MESSAGE
Max-Forwards: 70
User-Agent: Asterisk PBX 13.26.0
Content-Type: text/plain
Content-Length:    21

[redacted]
```

are in the same chat, however this message:

```
MESSAGE sip:my_sip_account@[2001:123:ab:123:4897:cde7:161a:d06d]:60151;transport=udp;app-id=755770037818;pn-type=firebase;pn-timeout=0;pn-tok==[redacted];pn-silent=1 SIP/2.0
Via: SIP/2.0/UDP [2001:123:ab:123::2]:5060;rport;branch=z9hG4bKPj2b7f1460-f5cd-4b39-a145-a0205cbff00b
From: "5565551212" <sip:[redacted]@pbx.example.com>;tag=b67ecf6e-90c9-44b1-9593-b0091cdb6326
To: <sip:my_sip_account@[2001:123:ab:123:4897:cde7:161a:d06d];app-id=755770037818;pn-type=firebase;pn-timeout=0;pn-tok==[redacted];pn-silent=1>
Contact: <sip:my_sip_account@[2001:123:ab:123::2]:5060>
Call-ID: d9c4b29f-3c08-4b10-a985-028a718e2ce7
CSeq: 44094 MESSAGE
Max-Forwards: 70
User-Agent: Asterisk PBX 13.26.0
Content-Type: text/plain
Content-Length:    19

[redacted]
```

from the same contact is in a different chat.  The only meaningful difference I can see in those is the IP address which is a result of being able to register to a multi-homed proxy/server.

**Comment by Viish** [comment] 2019-06-06 07:17
Duplicate of #605 and #627

**Closed by Viish** 2019-06-06 07:17 UTC
