### ISSUE TITLE
100rel in Linphone not working correctly

### ISSUE THREAD

**Issue by dabhi86** [BelledonneCommunications/linphone-android#1901] opened 2023-04-12 09:27 UTC
Hi Team Linphone,

I have used Support Level for 100Rel in my App by using "tag100RelSupportLevel" method and have set it to "SupportLevel.Mandatory" Is this enough to set up 100Rel?

Do I need to use some other functions as well to set it up correctly?

Your help is much appreciated.

Regards

**Comment by Viish** [comment] 2023-04-12 09:45
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1899, please continue conversation there if needed (even if closed).

And yes, it should be enough.

**Closed by Viish** 2023-04-12 09:45 UTC
