### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by skotow** [BelledonneCommunications/linphone-android#1578] opened 2021-12-21 22:26 UTC
Hello.  (Sorry for this but official documents does not have explanation on this I could say any explanation of methods and what exactly they do ) so will ask here .
I met problem that can't found answer for this . 
I want to know what is the way to create core or instantiate  it. 

when app is start first time , is everything fine is registering fine and working well , we have  own boolean method that will set to true if Registration state is OK . 
Our problem is when app is restarted  or was remove from list open apps on android or IOS , methods like ( core.defaultAccount is always be empty because after  restarting app all instances will be removed and is normal )  but problem is if we call again login sip with same credentials it will not reregister sip it will create new registration which will make problem after 5 registration to sip cost by over networking   same sip . 
Here  an example what we using for creating login or correct to say register sip with application . 

class BaseCore : Application() {

    companion object {

        private lateinit var core: Core
        fun factoryContext(context: Context) {
            val factory = Factory.instance()
            factory.setDebugMode(true, "Hello Linphone")
            core = factory.createCore(null, null, context)

        }

        fun getCore(): Core {
            return core
        }

    }

    // Create a Core listener to listen for the callback we need
    // In this case, we want to know about the account registration status
    private val coreListener = object : CoreListenerStub() {
        override fun onAccountRegistrationStateChanged(
            core: Core,
            account: Account,
            state: RegistrationState,
            message: String
        ) {
            // If account has been configured correctly, we will go through Progress and Ok states
            // Otherwise, we will be Failed.

            if (state == RegistrationState.Failed || state == RegistrationState.Cleared) {

            } else if (state == RegistrationState.Ok) {

            }
        }

        override fun onCallStateChanged(
            core: Core,
            call: Call,
            state: Call.State?,
            message: String
        ) {
            when (state) {
                Call.State.OutgoingInit -> {
                    // First state an outgoing call will go through
                    Log.e("Call", "$state")
                }
                Call.State.OutgoingProgress -> {
                    // Right after outgoing init
                    Log.e("Call", "$state")
                }
                Call.State.OutgoingRinging -> {
                    // This state will be reached upon reception of the 180 RINGING
                    Log.e("Call", "$state")
                }
                Call.State.Connected -> {
                    // When the 200 OK has been received
                    Log.e("Call", "$state")
                }
                Call.State.StreamsRunning -> {
                    // This state indicates the call is active.
                    // You may reach this state multiple times, for example after a pause/resume
                    // or after the ICE negotiation completes
                    // Wait for the call to be connected before allowing a call update

                    Log.e("Call", "$state")
                    // Only enable toggle camera button if there is more than 1 camera and the video is enabled
                    // We check if core.videoDevicesList.size > 2 because of the fake camera with static image created by our SDK (see below)

                }
                Call.State.Paused -> {
                    // When you put a call in pause, it will became Paused
                    Log.e("Call", "$state")
                }
                Call.State.PausedByRemote -> {
                    // When the remote end of the call pauses it, it will be PausedByRemote
                    Log.e("Call", "$state")
                }
                Call.State.Updating -> {
                    // When we request a call update, for example when toggling video
                    Log.e("Call", "$state")
                }
                Call.State.UpdatedByRemote -> {
                    // When the remote requests a call update
                    Log.e("Call", "$state")
                }
                Call.State.Released -> {
                    // Call state will be released shortly after the End state
                    Log.e("Call", "$state")
                }
                Call.State.Error -> {
                    Log.e("Call", "$state")
                }

            }

        }

    }

    fun login(
        user: List<User>,
        activity: Activity,
        port: TransportType = TransportType.Udp
    ) {

        var lists: List<User> = user

        val domain = "sip.server.example.net"
        // To configure a SIP account, we need an Account object and an AuthInfo object
        // The first one is how to connect to the proxy server, the second one stores the credentials

        for (list in lists) {

            // The auth info can be created from the Factory as it's only a data class
            // userID is set to null as it's the same as the username in our case
            // ha1 is set to null as we are using the clear text password. Upon first register, the hash will be computed automatically.
            // The realm will be determined automatically from the first register, as well as the algorithm
            val authInfo =
                Factory.instance()
                    .createAuthInfo(list.name, null, list.pass, null, null, domain, null)

            // Account object replaces deprecated ProxyConfig object
            // Account object is configured through an AccountParams object that we can obtain from the Core
            val accountParams = core.createAccountParams()

            // A SIP account is identified by an identity address that we can construct from the username and domain
            val identity = Factory.instance().createAddress("sip:${list.name}@$domain")
            accountParams.identityAddress = identity

            // We also need to configure where the proxy server is located
            val address = Factory.instance().createAddress("sip:$domain")
            // We use the Address object to easily set the transport protocol
            address?.transport = port
            accountParams.serverAddress = address
            // And we ensure the account will start the registration process

            accountParams.registerEnabled = CorePreferences(activity).isLogin()
            // Ensure push notification is enabled for this account
            accountParams.pushNotificationAllowed = true

            // Now that our AccountParams is configured, we can create the Account object
            val account = core.createAccount(accountParams)

            // Now let's add our objects to the Core
            core.addAuthInfo(authInfo)
            core.addAccount(account)

            account.addListener { _, state, message ->
                // There is a Log helper in org.linphone.core.tools package
                Log.e("Call", "$state")

                if (state == RegistrationState.Ok) {
                    CorePreferences(activity).storeLogin(false)

                    Log.e("JFJHFHFJK ", CorePreferences(activity).isLogin())
                }
            }

        }

        // Also set the newly added account as default
        core.defaultAccount = core.accountList.first()

        // Allow account to be removed

        // To be notified of the connection status of our account, we need to add the listener to the Core
        core.addListener(coreListener)
        // We can also register a callback on the Account object

        core.refreshRegisters()
        core.sessionExpiresEnabled = false
        core.setUserAgent("AppName", "1.0.1")
        // Finally we need the Core to be started for the registration to happen (it could have been started before)
        core.start()

    }

Does library has method that check if sip is already registered so just to make core.refreshRegister() on it ?

**Comment by Viish** [comment] 2021-12-22 12:03
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1568

**Closed by Viish** 2021-12-22 12:03 UTC
