### ISSUE TITLE
Speaker toggling - no audio

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#884] opened 2019-12-30 08:06 UTC
I had a closed issue #845. Related to that issue I found that this problem already was a tracked issue "No audio in calls after toggling speaker mode #794". Written that it is fixed in the linphone sdk, I test the latest version (4.3) with two android phones. One's version android 9.0 and the others' android 8.0. When I activate the speaker of android 9.0, android 8.0 does not hear any audio. When I disable the speaker (at the same call)the audio is received again. So toggling the speaker on android 9.0 phone causes android 8.0 phone to hear/not hear audio.

**Comment by Viish** [comment] 2019-12-30 09:48
Please attach logs from your Android 9 device from the start of the app to the end of a call with a speaker toggle.

**Comment by nzkar** [comment] 2019-12-30 10:19
Sure, there they are.

https://www.linphone.org:444//tmp/5e09cf48f345b_da0a6c94ce612746bb5a.gz

**Comment by nzkar** [comment] 2020-01-03 13:36
Hi, has there been any progress on this issue?

**Comment by Viish** [comment] 2020-01-13 13:04
Hi,
In your logs there is something weird: when you toggle the speaker, both the recorder and the player devices are disconnected, but only the player should be disconnected.

Can you capture full adb logcat logs when you toggle speaker during a call ?
Do you reproduce this issue with other devices ?
Are you using one of our AARs from our maven repository or are you building it yourself ?

Cheers,

**Comment by nzkar** [comment] 2020-01-15 10:37
Hi,

I can reproduce the error each time but I couldn't try with other phones. I have built it myself previously but this time I downloaded the app from google play store and I see the same error. I saved logs on the "about page" again and the link is https://www.linphone.org:444//tmp/5e1ed0af5caae_486d9b1c278695ce79a9.gz 

Since I use the application in the store, this is the only logs I have.

**Comment by Viish** [comment] 2020-01-22 17:33
Hi,
Can you try with another codec like Opus ?
Also do you still have the issue if you build a SDK without AAudio plugin?
Thanks in advance.

**Comment by nzkar** [comment] 2020-01-24 07:55
Since my sip service provider does not support Opus, I tried with GSM codec, same problem. I don't build the SDK anymore, I download the application from Google Play.

**Comment by noowenz** [comment] 2020-03-13 06:17
Hi @Viish,

I have been following this thread for a while and I have been facing same(Audio) issue on some of my devices that include(**OnePlus3** and **Samsung Galaxy A50**)

**Comment by alaskalinuxuser** [comment] 2020-05-27 11:51
I also have this issue from my Android 10 phone.

**Comment by Viish** [comment] 2020-05-27 12:40
@alaskalinuxuser with what version of Linphone-Android do you reproduce?

**Comment by alaskalinuxuser** [comment] 2020-05-27 13:05
Version 4.2.3 from F-Droid.

**Comment by alaskalinuxuser** [comment] 2020-05-27 13:34
I also tested version 4.1.1, 4.2.1, and 4.2.3. All three are available on F-Droid, and all three have the same issue. I can make calls, video calls, etc. But if I turn on the speaker, they cannot hear me. If I turn off the speaker, I can be heard. I tested with two different phones, both Android 10.

I really appreciate the great work put into this program, it's awesome, but it is impossible to do video chat without the speaker.

**Comment by Viish** [comment] 2020-05-27 13:44
Please enable debug logs (in advanced settings), restart the app, make a call to reproduce the issue and then send me logs (send logs button in about page)

**Comment by alaskalinuxuser** [comment] 2020-05-27 13:54
Will do. Here is the ADB logs I just pulled while waiting.
[linphoneADBlogcat.txt](https://github.com/BelledonneCommunications/linphone-android/files/4689185/linphoneADBlogcat.txt)

**Comment by alaskalinuxuser** [comment] 2020-05-27 13:57
And sent app log to you via email.

**Comment by Viish** [comment] 2020-05-27 15:47
Thanks.
Weird thing is from the logs everything is fine, you keep uploading audio (upload bandwidth isn't 0).
Could you attach the logs from the other device in the call that stops receiving audio please?

**Comment by alaskalinuxuser** [comment] 2020-05-27 15:56
In that log I sent you, I put both phones on speaker, one after the other. So the log I sent was on speaker and I couldn't hear on the other end, and the other phone was on speaker and I couldn't hear on this phone.
I hope that makes sense.

**Comment by alaskalinuxuser** [comment] 2020-05-27 16:02
To be thorough, here is the logs from the other phone. This time the other phone was not on speaker, so only my original phone was toggle speaker on, tried to talk, couldn't. Turn speaker off, talked, worked, turned speaker on, couldn't work.
https://www.linphone.org:444//tmp/5ece8e86a6216_3ade742d099a9c48b2b7.gz

**Comment by alaskalinuxuser** [comment] 2020-05-28 13:43
Okay, so I tested the new developer preview 5.0, and it "worked" but was very quiet. This led me to do some more fiddling, and I found out the issue, it is the same on the new dev preview and on the F-Droid app:

In both cases, the wrong microphone or wrong microphone settings are used. Because, when you switch to speaker, the speaker works great, but others can't hear anything (version 4.2) or it is very quiet (developer version). So, if, even though on speaker, I hold the phone to my head like a normal phone call, still no dice. However, while on speaker, if I hold the phone upside down against my head like a phone, then I can be heard just fine.

So it is either the wrong settings for the microphone, or choosing the wrong microphone for this use. It was "better" with the developer preview version you sent me, but still very quiet.

So, you were right, it is "normal" in the logs, because it is still sending audio, just not from the microphone or mic settings you normally have when using the speaker mode. For clarification, if I make a non Linphone, normal phone call with the phone's built in dialer, and choose to be on speaker mode, everything works fine, everyone can hear me, and I can hear everyone else. So the problem is specific to the Linphone Android app.

Hope that helps!

**Comment by alaskalinuxuser** [comment] 2020-05-28 14:14
With a little further digging, I think it may be choosing the wrong microphone, in my phone there is the "built in back mic" and the "built in mic" (ref: https://github.com/sonyxperiadev/device-sony-nile/blob/master/rootdir/vendor/etc/common_primary_audio_policy_configuration.xml#L10). If I look at my device audio platform info, I see this table:
    <acdb_ids>
        <device name="SND_DEVICE_OUT_SPEAKER" acdb_id="101"/>
        <device name="SND_DEVICE_OUT_SPEAKER_PROTECTED" acdb_id="101"/>
        <device name="SND_DEVICE_OUT_VOICE_SPEAKER_PROTECTED" acdb_id="101"/>
        <device name="SND_DEVICE_IN_CAPTURE_VI_FEEDBACK" acdb_id="102"/>
        <device name="SND_DEVICE_IN_VOICE_SPEAKER_DMIC" acdb_id="11"/>
        <device name="SND_DEVICE_OUT_VOICE_SPEAKER" acdb_id="101"/>
        <device name="SND_DEVICE_IN_VOICE_DMIC" acdb_id="41"/>
        <device name="SND_DEVICE_IN_BT_SCO_MIC" acdb_id="21"/>
        <device name="SND_DEVICE_IN_HANDSET_DMIC_AEC_NS" acdb_id="41"/>
        <device name="SND_DEVICE_IN_HEADSET_MIC_FLUENCE" acdb_id="8"/>
    </acdb_ids>
ref: https://github.com/sonyxperiadev/device-sony-nile/blob/master/rootdir/vendor/etc/audio_platform_info.xml#L57
However, in the logcat I sent you above, it is switching from acdb id 41 ("SND_DEVICE_IN_VOICE_DMIC") to acdb id 117. But acdb id 117 is not on the list, which is odd to me, since it does exist as the rear facing camcorder speaker.

But, when I use the built in phone dialer (non-Linphone) and turn on the speaker, it switches from acdb id 41 ("SND_DEVICE_IN_VOICE_DMIC") to acdb id 11 ("SND_DEVICE_IN_VOICE_SPEAKER_DMIC"), which works as expected.

So, the Linphone app switches to the wrong microphone, switching to the camcorder rear facing microphone, instead of the front facing speaker microphone.

Probably more than you wanted to know, but I hope that helps!

**Comment by Viish** [comment] 2020-05-28 14:22
Thanks for the information, I'll see what I can do.

**Comment by Viish** [comment] 2020-06-22 12:17
Fixed in master banch of SDK when AAudio plugin is built.

Can also be fixed by cherry-picking mediastreamer2 fix/opensles_mic_switch_in_speaker branc and setting the DEVICE_OPENSLES_MIC_SWITCH_WHEN_IN_SPEAKER flag for the device `using core.mediastreamerFactory.setDeviceInfo()` method.

**Closed by Viish** 2020-06-22 12:17 UTC
