### ISSUE TITLE
Callee get the first frame is bad

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1725] opened 2022-07-15 03:19 UTC
Hi Viish,

My device is Linphone-android, and I set video :15fps,  VGA,
AMediaFormat_setString(format, "mime", "video/avc");
	AMediaFormat_setInt32(format, "width", d->vconf.vsize.width);
	AMediaFormat_setInt32(format, "height", d->vconf.vsize.height);
	AMediaFormat_setInt32(format, "i-frame-interval", 1);   
	AMediaFormat_setInt32(format, "bitrate", (d->vconf.required_bitrate * 9)/10); /*take a margin*/
	AMediaFormat_setInt32(format, "frame-rate", d->vconf.fps);
	AMediaFormat_setInt32(format, "bitrate-mode", 1);
	AMediaFormat_setInt32(format, "profile", 1); // AVCProfileBaseline
	AMediaFormat_setInt32(format, "level", 1024); // AVCLevel32

callee devices is not linphone-android, When calling, there is a problem with the first frame received by callee device, which may not be I frame, so half of the first picture displayed by callee device is green. How to solve this?

thanks,
Best Regards.

**Comment by fengqz627** [comment] 2022-07-15 03:24
My linphone-android devices is caller, and send video to callee ,and callee is not linphone-android, and recives video ,but the first frame is bad. so ,callee will display the green screen at first, and then it will be normal.

**Comment by Viish** [comment] 2022-07-15 07:11
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1724

**Closed by Viish** 2022-07-15 07:11 UTC
