### ISSUE TITLE
java.lang.NullPointerException trying to open dialogues```

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#833] opened 2019-11-19 18:01 UTC
I've received a new "bad" message, and I'm not able to open dialogues more. Pressing the ![image](https://user-images.githubusercontent.com/14617699/69172836-9cb8e780-0b0f-11ea-93ad-e66a597e0e6e.png) button gives:

```
11-19 20:54:43.582 30405 30405 D AndroidRuntime: Shutting down VM
11-19 20:54:43.583 30405 30405 E AndroidRuntime: FATAL EXCEPTION: main
11-19 20:54:43.583 30405 30405 E AndroidRuntime: Process: org.linphone, PID: 30405
11-19 20:54:43.583 30405 30405 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at java.util.regex.Matcher.reset(Matcher.java:1059)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at java.util.regex.Matcher.<init>(Matcher.java:187)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at java.util.regex.Pattern.matcher(Pattern.java:1010)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at org.linphone.contacts.j.a(ContactsManager.java:17)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at org.linphone.chat.g.c(ChatRoomViewHolder.java:6)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at org.linphone.chat.g.a(ChatRoomViewHolder.java:15)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at org.linphone.chat.h.a(ChatRoomsAdapter.java:9)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at org.linphone.chat.h.b(ChatRoomsAdapter.java:1)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$g.a(RecyclerView.java:1)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$g.a(RecyclerView.java:14)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$v.a(RecyclerView.java:8)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$v.a(RecyclerView.java:73)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$v.b(RecyclerView.java:1)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$v.d(RecyclerView.java:11)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:4)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:145)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:132)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.e(LinearLayoutManager.java:59)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at org.linphone.views.LinphoneLinearLayoutManager.e(LinphoneLinearLayoutManager.java:1)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.B(RecyclerView.java:8)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.c(RecyclerView.java:31)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1801)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1567)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.View.layout(View.java:20693)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-19 20:54:43.583 30405 30405 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-19 20:54:43.585  2413  9639 W ActivityManager:   Force finishing activity org.linphone/.chat.ChatActivity
11-19 20:54:43.588  2413  9639 W ActivityManager:   Force finishing activity org.linphone/.activities.DialerActivity
11-19 20:54:43.594  2413  2476 I ActivityManager: Showing crash dialog for package org.linphone u0
```

**Comment by Viish** [comment] 2019-11-20 09:08
Should be fixed in 260d38669e34e981e7d4db33fb346833ee00137d

**Closed by Viish** 2019-11-20 09:08 UTC

**Comment by 532910** [comment] 2019-11-21 02:00
While it doesn't crash more, the messages tab looks very strange. The link to the screen record sent via e-mail, as it contains some private data.

**Comment by Viish** [comment] 2019-11-21 08:15
Can you enable library logs, reproduce the scenario in the video you sent me and then send me logs ?

**Comment by 532910** [comment] 2019-11-21 19:53
Sure, sent.

**Comment by Viish** [comment] 2019-11-22 09:18
I believe this is due to the bad SIP URI of the sender:
```
2019-11-21 22:46:42:566 [belle-sip] ERROR fast_header_address parser error for [sip:MegaFon OFD@outerface.net]
2019-11-21 22:46:42:566 [liblinphone] WARNING Cannot create Address, bad uri [sip:MegaFon OFD@outerface.net]
```
It doesn't respect the SIP RFC, so our parser has trouble with it, and that causes a lot of unwanted behaviors in the SDK and thus the app.

**Comment by Viish** [comment] 2019-11-22 09:57
Regarding the "bad" message, can you reproduce it's reception ?
It would help understand why it hasn't been catched by our security.

**Comment by 532910** [comment] 2019-11-22 15:46
That message is a confirmation for mobile phone account refillment, so I can easily reproduce it.
Do you need only the library log?

**Comment by Viish** [comment] 2019-11-22 15:52
Yes please.

**Comment by Viish** [comment] 2019-11-26 09:47
Actually was a SDK issue. Fixed in linphone-sdk 132d630dd89eac6ad6f360d85c3954e6d662d01b

**Comment by 532910** [comment] 2019-11-30 09:20
Can I test it with 4.3.0-beta.31+7a194d5?

**Comment by Viish** [comment] 2019-11-30 18:25
Yes the latest beta has the fix.

**Comment by 532910** [comment] 2019-12-02 11:16
Hm, I repeated the payment, and received the same messages without issues, but now I see an empty `sip:` message every time I restart linphone. A screen record with log are sent by e-mail.

**Comment by Viish** [comment] 2019-12-02 11:18
A different one that the one you had previously ?

**Comment by Viish** [comment] 2019-12-02 11:20
From the video it looks OK, the message you reveived from the sender with the space in the username is correctly displayed.

**Comment by 532910** [comment] 2019-12-02 11:21
Yes, but it creates en empty `sip:` message on linphone restart.

**Comment by Viish** [comment] 2019-12-02 11:23
I believe this is the one that was created before the update.
Sadly we can't delete it as it is the result of a bug.
If you uninstall the app (or at least clean the data) and reproduce the scenario you shouldn't have it anymore.

**Comment by 532910** [comment] 2019-12-02 11:25
OK, I'll do a new test with the app reinstallation!

**Comment by 532910** [comment] 2019-12-09 18:47
I confirm, there no more empty `sip:` message.
