### ISSUE TITLE
segfault in ICE handling

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1353] opened 2021-04-09 13:16 UTC
I'm getting this segfault while trying to make a call with ICE enabled on 4cb9c914f:

```
04-09 08:46:44.525  7609  7609 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-09 08:46:44.526  7609  7609 F DEBUG   : LineageOS Version: '18.1-20210328-UNOFFICIAL-hammerhead'
04-09 08:46:44.526  7609  7609 F DEBUG   : Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys'
04-09 08:46:44.526  7609  7609 F DEBUG   : Revision: '11'
04-09 08:46:44.526  7609  7609 F DEBUG   : ABI: 'arm'
04-09 08:46:44.526  7609  7609 F DEBUG   : Timestamp: 2021-04-09 08:46:44-0400
04-09 08:46:44.526  7609  7609 F DEBUG   : pid: 7457, tid: 7457, name: .linphone.debug  >>> org.linphone.debug <<<
04-09 08:46:44.527  7609  7609 F DEBUG   : uid: 10280
04-09 08:46:44.527  7609  7609 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-09 08:46:44.527  7609  7609 F DEBUG   : Cause: null pointer dereference
04-09 08:46:44.527  7609  7609 F DEBUG   :     r0  00000000  r1  00000000  r2  00000000  r3  00000000
04-09 08:46:44.527  7609  7609 F DEBUG   :     r4  00000000  r5  7fa8d170  r6  00000000  r7  befbd3e0
04-09 08:46:44.527  7609  7609 F DEBUG   :     r8  00000000  r9  00000000  r10 7fa8d174  r11 7ee255e8
04-09 08:46:44.527  7609  7609 F DEBUG   :     ip  7d8f00dc  sp  befbd3c8  lr  7d6273cf  pc  a75e508c
04-09 08:46:44.712  7609  7609 F DEBUG   : backtrace:
04-09 08:46:44.713  7609  7609 F DEBUG   :       #00 pc 0005f08c  /apex/com.android.runtime/lib/bionic/libc.so (strlen_a15+72) (BuildId: 5d93fe6bae0cd87b6ef9acd424a4e45b)
04-09 08:46:44.713  7609  7609 F DEBUG   :       #01 pc 000a33cb  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/libmediastreamer.so (BuildId: d5d73fd53dab4277e38d7a51bd44efa828c7ec48)
04-09 08:46:44.713  7609  7609 F DEBUG   :       #02 pc 0055cba9  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (LinphonePrivate::IceService::checkForIceRestartAndSetRemoteCredentials(std::__ndk1::shared_ptr<LinphonePrivate::SalMediaDescription> const&, bool)+572) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.713  7609  7609 F DEBUG   :       #03 pc 0055c3f7  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (LinphonePrivate::IceService::updateFromRemoteMediaDescription(std::__ndk1::shared_ptr<LinphonePrivate::SalMediaDescription> const&, std::__ndk1::shared_ptr<LinphonePrivate::SalMediaDescription> const&, bool)+42) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.713  7609  7609 F DEBUG   :       #04 pc 0055d26b  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (LinphonePrivate::IceService::render(LinphonePrivate::OfferAnswerContext const&, LinphonePrivate::CallSession::State)+24) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.713  7609  7609 F DEBUG   :       #05 pc 0051748d  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (LinphonePrivate::StreamsGroup::render(LinphonePrivate::OfferAnswerContext const&, LinphonePrivate::CallSession::State)+648) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.713  7609  7609 F DEBUG   :       #06 pc 00505e8d  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (LinphonePrivate::MediaSessionPrivate::updateStreams(std::__ndk1::shared_ptr<LinphonePrivate::SalMediaDescription>&, LinphonePrivate::CallSession::State)+820) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.714  7609  7609 F DEBUG   :       #07 pc 00504431  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (LinphonePrivate::MediaSessionPrivate::accepted()+1184) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.714  7609  7609 F DEBUG   :       #08 pc 005f39cb  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.714  7609  7609 F DEBUG   :       #09 pc 0056287d  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (LinphonePrivate::SalCallOp::processResponseCb(void*, belle_sip_response_event const*)+1592) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.714  7609  7609 F DEBUG   :       #10 pc 0056f665  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (LinphonePrivate::Sal::processResponseEventCb(void*, belle_sip_response_event const*)+960) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.714  7609  7609 F DEBUG   :       #11 pc 006863ab  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (belle_sip_client_transaction_notify_response+366) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.714  7609  7609 F DEBUG   :       #12 pc 006816c3  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (belle_sip_provider_dispatch_message+1030) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.714  7609  7609 F DEBUG   :       #13 pc 00670243  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.714  7609  7609 F DEBUG   :       #14 pc 0066f09b  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (belle_sip_channel_process_data+210) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.714  7609  7609 F DEBUG   :       #15 pc 00686fab  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #16 pc 00668115  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (belle_sip_main_loop_run+748) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #17 pc 006682ed  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (belle_sip_main_loop_sleep+40) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #18 pc 00607cfb  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/lib/arm/liblinphone.so (linphone_core_iterate+322) (BuildId: e2468c3dd3c4de8402acb432a54822d2449bb46c)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #19 pc 0005967b  /data/app/~~Huu1LhibRYHbOGZJ2Am6dA==/org.linphone.debug-wozCnbh5y_5rbaGsTHa_Jg==/oat/arm/base.odex (art_jni_trampoline+82)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #20 pc 0201c25b  /memfd:jit-cache (deleted) (offset 0x2000000) (org.linphone.core.CoreImpl.iterate+58)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #21 pc 020316e7  /memfd:jit-cache (deleted) (offset 0x2000000) (org.linphone.core.tools.service.CoreManager$1.run+78)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #22 pc 000d39d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #23 pc 004f8331  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+280) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #24 pc 0012c09f  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+142) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #25 pc 0024049f  /apex/com.android.art/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+250) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.715  7609  7609 F DEBUG   :       #26 pc 002389a7  /apex/com.android.art/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+746) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #27 pc 004eb105  /apex/com.android.art/lib/libart.so (MterpInvokeInterface+876) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #28 pc 000ce614  /apex/com.android.art/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #29 pc 0035d570  /system/framework/framework.jar (offset 0x84a000) (android.os.Handler.handleCallback+4)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #30 pc 004ec6a7  /apex/com.android.art/lib/libart.so (MterpInvokeStatic+1046) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #31 pc 000ce594  /apex/com.android.art/lib/libart.so (mterp_op_invoke_static+20) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #32 pc 0035d3e4  /system/framework/framework.jar (offset 0x84a000) (android.os.Handler.dispatchMessage+8)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #33 pc 004e9c9b  /apex/com.android.art/lib/libart.so (MterpInvokeVirtual+1290) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #34 pc 000ce414  /apex/com.android.art/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #35 pc 0038459c  /system/framework/framework.jar (offset 0x84a000) (android.os.Looper.loop+480)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #36 pc 0023175f  /apex/com.android.art/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.11748362637241545724)+250) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.716  7609  7609 F DEBUG   :       #37 pc 002381d7  /apex/com.android.art/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+138) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #38 pc 0023910b  /apex/com.android.art/lib/libart.so (bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1474) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #39 pc 00106bb1  /apex/com.android.art/lib/libart.so (void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*)+49680) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #40 pc 000d9075  /apex/com.android.art/lib/libart.so (ExecuteSwitchImplAsm+4) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #41 pc 00197368  /system/framework/framework.jar (android.app.ActivityThread.main)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #42 pc 0023171d  /apex/com.android.art/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.11748362637241545724)+184) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #43 pc 00238113  /apex/com.android.art/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+114) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #44 pc 004db069  /apex/com.android.art/lib/libart.so (artQuickToInterpreterBridge+684) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #45 pc 000d8561  /apex/com.android.art/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #46 pc 000d39d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #47 pc 004f8461  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+276) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #48 pc 0012c0b1  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+160) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.717  7609  7609 F DEBUG   :       #49 pc 00404701  /apex/com.android.art/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+820) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.718  7609  7609 F DEBUG   :       #50 pc 003a3dc7  /apex/com.android.art/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+30) (BuildId: a300af774b3f04f431ac5e72592a86a3)
04-09 08:46:44.718  7609  7609 F DEBUG   :       #51 pc 0008363f  /apex/com.android.art/javalib/arm/boot.oat (BuildId: 80a5b7b68d524e7515cf8cbf95608e32899dff65)
```

More complete [`adb logcat`](http://brian.interlinx.bc.ca/linphone-segfault.txt)

Disabling ICE makes the call work.  But disabling ICE seriously impacts the usefulness/functionality of linphone across NAT etc.

**Comment by Viish** [comment] 2021-04-09 13:21
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/137
Please don't reopen issues I move around...

**Closed by Viish** 2021-04-09 13:21 UTC

**Comment by brianjmurrell** [comment] 2021-04-09 17:10
I did not intentionally reopen an issue you moved.

I did not get any notification (whatsoever) of the move and not seeing the issue in this project ths morning when I went looking for it suggested to me that either I only imagined opening it, or that GitHub burped and lost it after I created it.
