### ISSUE TITLE
Build linphone sdk with openh264 failed

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-android#824] opened 2019-11-11 03:38 UTC
I cloned a project on branch master and build with enable openh264 option and I got this error

Scanning dependencies of target EP_openh264
[ 76%] Creating directories for 'EP_openh264'
[ 76%] No download step for 'EP_openh264'
[ 76%] No patch step for 'EP_openh264'
[ 77%] No update step for 'EP_openh264'
[ 77%] Performing configure step for 'EP_openh264'
[ 77%] Forcing build for 'EP_openh264'
[ 77%] Performing build step for 'EP_openh264'
../../../../..//external/openh264/build/platform-android.mk:54: *** Compiler not found, bad NDKROOT or ARCH?. Stop.
make[5]: *** [/Users/sarunyuprasert/Documents/Git_Linphone_SDK_Android_4_3/linphone-sdk/build/WORK/android-armv7/Stamp/EP_openh264/EP_openh264-build] Error 2
make[4]: *** [CMakeFiles/EP_openh264.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [android-armv7-prefix/src/android-armv7-stamp/android-armv7-build] Error 2
make[1]: *** [CMakeFiles/android-armv7.dir/all] Error 2
make: *** [all] Error 2

**Comment by github-karthik** [comment] 2019-11-11 09:48
Which version NDK you are using ?

**Comment by SarunyuPrasert** [comment] 2019-11-11 13:09
NDK version r20

**Comment by github-karthik** [comment] 2019-11-11 17:08
For me its working fine  release/4.2 branch , NDK 20v  . make sure you add NDK path like 
export ANDROID_NDK_ROOT="your_ndk_path" .  Not an issue consider closing this .

**Comment by SarunyuPrasert** [comment] 2019-11-12 02:22
Yes. For release/4.2 brach I cam build pass with no openh264 codec error,
but this error happened on branch release/4.3 and above (alpha or beta
version) the reason I have to use 4.3 above is I have to use option camera2
but camera2 is no problem

**Comment by Viish** [comment] 2019-11-19 10:02
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/2
We're working on it.

**Closed by Viish** 2019-11-19 10:02 UTC
