### ISSUE TITLE
Factory issues

### ISSUE THREAD

**Issue by skotow** [BelledonneCommunications/linphone-android#1596] opened 2022-01-31 09:20 UTC
Each time  app open after removing from,  list open apps, 
 ```
 fun ensureCoreExists(context: Context) {
            if (::coreContext.isInitialized) {
                Log.w("CREATING", "[Application] Skipping Core creation")
                return

            }
            val basePath = context.filesDir.absolutePath
            val mConfigFactoryFile = "$basePath/linphonerc";
            val mLinphoneConfigFile = "$basePath/.linphonerc";
            val factoryConf = Factory.instance()
                .createConfigWithFactory(mLinphoneConfigFile, mConfigFactoryFile)
            Factory.instance().setDebugMode(true, "Hello Linphone")
            Factory.instance().setLogCollectionPath(context.filesDir.absolutePath)
            Factory.instance().enableLogCollection(LogCollectionState.Enabled)
            coreContext = CoreContext(context, factoryConf)
            coreContext.start()

        }
```

is registering sip on the server each time is opens app, which cost problems with limit of registration on server . 
 
What matter cost this behavior ?

**Comment by NLLAPPS** [comment] 2022-01-31 09:33
"Each time app open after removing from, list open apps" Closing an ap from recent apps kills the app on most Chinese OEMs. You can try applying settings related to your phone from https://dontkillmyapp.com

**Comment by Viish** [comment] 2022-02-01 10:18
That is the intended behavior.

When your app starts, it must REGISTER to the SIP proxy in order to be known from it and to receive any INVITE or MESSAGE the proxy has for it.

**Closed by Viish** 2022-02-01 10:18 UTC
