### ISSUE TITLE
Can't sign in linphone

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1652] opened 2022-04-14 10:52 UTC
Hi，

when Sign in , I can't log in to my account and always display “invalid login or password” ,Log in occasionally， it shows “sorry,something went wrong" under my name, and I can't quit，What's the problem？

thanks.

**Comment by Viish** [comment] 2022-04-14 11:58
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1651

**Closed by Viish** 2022-04-14 11:58 UTC
