### ISSUE TITLE
Sip Message and Sip Subscribe Events weird behaviour

### ISSUE THREAD

**Issue by nick2601** [BelledonneCommunications/linphone-android#1294] opened 2021-02-19 13:39 UTC
@Viish 
1)I am expected to receive a Sip Message event  upon successful registration from the server and the message which I will be consuming into the App is a multipart/mixed body with 2 different Content Types "a" and "b", which are unsupported by stack.For the message to be consumed by the App I am using core.onMessageReceived callback from CoreListener class and core.addContentType support for the   unsupported contents ,but still I get to see the same error Unsupported Content type for the given Content Types.
2)Apart from that when my Message(Incoming from server) is rejected , a new Sip Message(android) is generated automatically (I am not generating this event) ,and sent to server with some weird string in the content body resulting in crash of server.
3)Whenever I try to deregister an account and try re-register the same account upon successful registration a Sip Subscribe Event is going out of linphone to **<sip:rls@linphone.org>**

**SDK logs**
 (https://www.linphone.org:444//tmp/602e2f17ed796_24b09505144b4a840fd3.gz)

**Screenshots**
![RejectedMessage on Client](https://user-images.githubusercontent.com/59530213/108344135-c6752880-7202-11eb-9d3c-a03733eab2e0.png)
![AutogeneratedMessageWithWeirdString](https://user-images.githubusercontent.com/59530213/108343137-99744600-7201-11eb-875a-79856e4b3e20.png)
![SipMessageFromServer](https://user-images.githubusercontent.com/59530213/108343261-c0327c80-7201-11eb-90a4-870e0210c9c5.png)
![SipSubscribe](https://user-images.githubusercontent.com/59530213/108343289-c7f22100-7201-11eb-9414-8d6fc82ec0bc.png)

Thanks in advance for your valuable feedback

**Comment by Viish** [comment] 2021-02-22 13:47
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/116

**Closed by Viish** 2021-02-22 13:47 UTC
