### ISSUE TITLE
Clarify when some configs are registered and others are not

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#547] opened 2019-04-03 11:11 UTC
I have multiple proxy configs and when at least one of them is unregistered (because it's disabled) here's what the UI is shows:

![Screenshot_20190403-070137](https://user-images.githubusercontent.com/559317/55474298-c2c06480-55de-11e9-9436-90cb3ab7d331.jpg)

This is very misleading.  It makes me believe I am completely unregistered and won't receive calls.  But in fact one of my configs is enabled and registered and the other is actively disabled (not enabled but just unregistered).

Can this UI element be clarified?  Perhaps instead of just one green/grey dot there should a dot for each config, and perhaps the color of the dot should reflect the state more clearly.  Green for enabled and registered.  Red for enabled and not registered and grey for disabled.  Maybe that's what it already is, but just wanted to add that in case it's not.

**Comment by Viish** [comment] 2019-04-03 14:06
This dot reflects the status of the default proxy config.
All proxy configs states can be checked in the side menu.
If we added a dot per proxy config it wouldn't be clearer for the user, and for most of them they only have 1 account.

**Closed by Viish** 2019-04-03 14:06 UTC

**Comment by brianjmurrell** [comment] 2019-04-03 14:11
> If we added a dot per proxy config it wouldn't be clearer for the user,

How wouldn't it?  If the colour of the dots followed my scheme above (green for enabled and registered. red for enabled and not registered and grey for disabled) I think it would be abundantly clear, much more clear that it is currently.

> and for most of them they only have 1 account.

And so this change would not affect them.

So what is the problem with making a change that will only affect a smaller number of users but will affect them in a way that makes things more clear for them?

**Comment by Viish** [comment] 2019-04-03 14:16
The problem is we can't make a change in the UI like that.
There is a process to be followed, and this process has been closed for this release.
Next release will have a major redesign, we'll keep your suggestion in mind at that time.

**Comment by brianjmurrell** [comment] 2019-04-03 15:32
So then why is the issue closed if it will be considered for a subsequent release?

Can you please reopen this so that I, you and others can see that this is on a roadmap?

**Comment by Viish** [comment] 2019-04-03 15:41
This isn't an issue and this is not on the roadmap. 
I said we'll consider it when we'll redesign the application, which it isn't even planned.
I want to have a clear view of the real issues, and this ain't one.

**Comment by brianjmurrell** [comment] 2019-04-03 15:44
That's what the project planning features of GitHub are for.

You shouldn't just summarily close issues that may have a longer shelf-life than your next release.

**Comment by Viish** [comment] 2019-04-03 15:47
First of all, github is merely a mirror of our own gitlab, it simply has a backup and visibility purpose.
Secondly, we are a compagny and our choices are made firstly for our customers. I could also have told you that we won't even consider it.
Finally, since the project is open-source, you are free to fork it and make you own custom changes, specifically for something so minor.
