### ISSUE TITLE
when user is in video call if 1st user disabled video so screen will become black for  2nd user  so there is any callback in linphone to detect this scenario?

### ISSUE THREAD

**Issue by namanbansal161995** [BelledonneCommunications/linphone-android#647] opened 2019-05-22 05:55 UTC
We are building an app in which we have video call feature so there is video disable and enable feature in it. when user 1 disabled video and screen become black (surface view become black) for 2nd user there is any method which i can call to detect the callbacks when user disabled video while in video call

**Comment by Viish** [comment] 2019-05-22 07:17
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/643

**Closed by Viish** 2019-05-22 07:17 UTC
