### ISSUE TITLE
Phone only vibrates once when a phone call comes in

### ISSUE THREAD

**Issue by Peter4487** [BelledonneCommunications/linphone-android#1794] opened 2022-11-15 01:34 UTC
Hi,
I'm not sure if this is as-designed or a bug.

- When receiving a phone call, I get a quick "buzz-buzz" and then nothing.
- - What I expect is for the phone to continue vibrating until the phone stops ringing or I decline / accept the call.
- If I allow an audible ringtone, the audible ringtone works properly.
- The linphone setting "Use device ringtone" is True, though I see the same behavior with False
- The linphone setting "Vibrate while incoming call is ringing" is True, though I see the same behavior with False
- The device setting is to vibrate with call ringing, no ascending ringing sound

If this is a bug let me know and I'll supply logs.

Pixel 5 running newest Android

**Comment by Viish** [comment] 2022-11-15 08:41
HI @Peter4487,

Yes, please attach logs.
Thanks!

**Comment by Viish** [comment] 2022-11-21 09:55
Hi @Peter4487 ,

Any update?

**Comment by Peter4487** [comment] 2022-11-21 20:54
Here you go (IPs, cryptographic keys, domains, numbers, etc. obfuscated--I don't know what's supposed to be secret and what's okay to share :-)
[linphone_logs_one_vibration.txt](https://github.com/BelledonneCommunications/linphone-android/files/10060448/linphone_logs_one_vibration.txt)

**Comment by Viish** [comment] 2022-11-22 08:21
Thanks, but there is something I don't understand.
Can you attach logs from the start of the app to the end of the incoming call please?

**Comment by Peter4487** [comment] 2022-11-22 15:33
[linphone_logs_one_vibration_2.txt](https://github.com/BelledonneCommunications/linphone-android/files/10068799/linphone_logs_one_vibration_2.txt)

Attached, thanks Viish

**Comment by Viish** [comment] 2022-11-22 15:58
Thanks! 
I see what the issue is, it should have been fixed in current public 4.7.0-beta.
You can find it in the Play Store or as one of our nightly build: https://download.linphone.org/snapshots/android/
Can you confirm issue is fixed on your device as well please?

**Comment by Peter4487** [comment] 2022-11-22 16:10
Thanks very much for taking a look Sylvain.

I installed the nightly, but it installs alongside my existing linphone (rather than replacing it). There isn't an easy way to export / import settings so I think I'll wait until 4.7 is on F-Droid to test (since setup takes a while by hand). I know of the remote config route, but it's not exposed in the front end.

Thanks again!

**Comment by Viish** [comment] 2022-11-22 16:32
Ok don't worry in the meantime I found a way to reproduce your issue even on the current beta and I have a fix for it: https://gitlab.linphone.org/BC/public/linphone-sdk/-/merge_requests/3236

So it will be part of next release to come :)

**Closed by Viish** 2022-11-22 16:32 UTC
Labels: status: feedback
