### ISSUE TITLE
linphone on android, stops connect automatically at startup after few days

### ISSUE THREAD

**Issue by lm2lm2** [BelledonneCommunications/linphone-android#2171] opened 2024-05-30 17:42 UTC
First of all, please say "Hi" or "Hello", it doesn't cost much.
Hi !

1. **Describe the bug** (mandatory)

linphone installed on several various android devices

after few days of being not used (the app, not the device), call various linphone-account or third-part-accounts registred within the android linphone app, just doesnt makes it ring, even connected to the internet

[we dont use playstore nor any google services]

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

2. **To Reproduce** (mandatory)

a. install linphone
b. add linphone account + others SIP providers accounts
c. use them just to test if it works well
d. just let few days/weeks pass (with "remove autorizations after 30 days" disabled)
e. just try to call on any account present on linphone app => nothing rings, a bit like if linphone is just not running.

3. **Expected behavior** (mandatory)

to get linphone connecting to sip providers each time the device is connected to the internet, and ring when the account is called

4. **Please complete the following information** (mandatory)

 - Device: various, several models
 - OS: various from android 7 to higher 
 - Version of the App also very various
 - Version of the SDK same
 - Where you did got it from fdroid
 - Please tell us if your Android is a Lineage OS or another variant : samsung official android, graphene, lineageos and others

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)

i cannot grab all logs as i dont have the phone myself, they are used with their owners

6. **Adb logcat logs** (mandatory if native crash)

not applicable

7. **Screenshots** (optionnal)

not applicable
8. **Additional context** (optionnal)

app was working well a week or two just before.
now we have to open manually the lniphone app to get everything back, but it's not a correct thing, that forces all users to open very frequently the app, even if we communicate through it only 1 or 2 times per month. Problem is that we have to ask to users to open it manually, instead of call directly to the registred account.
a bit like a wake up shake by opening the app, instead of having it connected in background (like signal telegram etc)

additional parameters :+1: 
the service linphone runs well and appear wells in notification, while disappears with no other clue after few days (it took few weeks to figure out this)
-the background option in advanced settings, is "enabled" on all andro/linphone
-the battery optimization settings is well disabled also for all devices (and linphone is the only one to get this kind of bug, as other apps also benefits from non optimization and are everytime in notification service zone)
-the "remove permissions if app isnt used" is also well disabled on all device since the beginning

-some devices run behind free vpn, but run wells even behind those vpn. just "wake up" by opening the linphone app make things properly back. VPN is not the problem.

Thank you in advance for filling bug reports properly!
you're welcome

edit 1 :+1: 
in attachment, the anonymized log about a first xperia using ungoogle lineageos (LOS 20), with same symptom : even in battery saving mode, for few days linphone works perfect, until one or several weeks after then linphone doesnt responds at all (and others apps with same "non battery optimized" settings are perfectly still in notification surveillance wakeup, just linphone "vanishes" like that (even if nothing has been changed)
on this log, it's the afternoon of the 30th of may, a bit before 7PM that the linphone service was seen as "not responding at all", with all calls being as "busy", until app was reopened and everything worked back. But it asks to shake back the app.

[Uploading linphone_logs__Andro5.2.3__sdk5.3.19__lineageoswithoutgoogle.txt…]()

i just added for a samsung a10 with default android on it (andro11), where i forgotten a while ago to enable logs, and it's the same on a pixel 6A where the logs were not enabled : now it's done, lets meet next months to experience if linphone service still vanish after few days or weeks of non usage..

**Comment by Viish** [comment] 2024-05-31 07:32
Hi @lm2lm2,

This background mode was always a workaround, as Android doesn't like having an app that's always running.
Up until now it was kinda working, depending on the device manufacturer (maybe you remember https://dontkillmyapp.com).
With Android 15 that will be released in a few months, they are definitively killing that: a foreground datasync service will only be allowed 6 hours every day, so this mode will no longer be a solution when push notifications aren't available...

That being said, if it was working before and no longer does, it's likely because LineageOS changed something about that, as we didn't.
I couldn't check your logs because the link simply redirects towards the github issue, could you attach it again so I can confirm everything goes as expected in our app?

Cheers,

**Comment by lm2lm2** [comment] 2024-05-31 11:36
> Hi @lm2lm2,
> 
> This background mode was always a workaround, as Android doesn't like having an app that's always running. Up until now it was kinda working, depending on the device manufacturer (maybe you remember https://dontkillmyapp.com). With Android 15 that will be released in a few months, they are definitively killing that: a foreground datasync service will only be allowed 6 hours every day, so this mode will no longer be a solution when push notifications aren't available...
> 
> That being said, if it was working before and no longer does, it's likely because LineageOS changed something about that, as we didn't. I couldn't check your logs because the link simply redirects towards the github issue, could you attach it again so I can confirm everything goes as expected in our app?
> 
> Cheers,

hello
[xperia_linphone_lineageos_logs.txt](https://github.com/user-attachments/files/15512921/xperia_linphone_lineageos_logs.txt)


here is the log  

on my side, i dont know but it's doing the same on default samsung galaxy android, on pixel/graphene and on xperia/lineage.
but it does it only after few days..

**Comment by Viish** [comment] 2024-05-31 13:16
Thanks for the logs, but from them I can't tell you why the app is being killed, the OS isn't very verbose about it:
```
2024-05-30 12:29:15:666 [org.linphone/linphone-android] MESSAGE ==== Previous exit reason information dump ====
2024-05-30 12:29:15:666 [org.linphone/linphone-android] MESSAGE REASON=Signaled
2024-05-30 12:29:15:667 [org.linphone/linphone-android] MESSAGE TIMESTAMP=03-05-2024 16:53:59
2024-05-30 12:29:15:667 [org.linphone/linphone-android] MESSAGE DESCRIPTION=null
```

**Closed by Viish** 2024-05-31 13:16 UTC

**Comment by xiezhouyan1027** [comment] 2024-09-23 09:54
Your problem looks like the device is disconnected from the server. Check whether the battery optimization of the app is on. Please turn off battery optimization.

**Comment by EmanuelLoos** [comment] 2026-03-04 08:23
Implementing UnifiedPush would be the best solution, but if that cannot be done for some reason, you might want to take a look at how Conversations implements its background service, because that one still works very well for me: https://codeberg.org/iNPUTmice/Conversations
