### ISSUE TITLE
Crash during attaching photo when file size >10MB

### ISSUE THREAD

**Issue by ecogava** [BelledonneCommunications/linphone-android#2184] opened 2024-06-16 18:49 UTC
1. **Describe the bug** (mandatory)

Description placed in title*

2. **To Reproduce** (mandatory)

Try to attach photo with file size more than 10MB

3. **Expected behavior** (mandatory)

Send photo

4. **Please complete the following information** (mandatory)

 - Device: more than 3 different devices
 - OS: 12-14
 - Version of the App: latest
 - Version of the SDK: latest
 - Where you did got it from: different sources
 - Please tell us if your Android is a Lineage OS or another variant: different ROMs

If you are using a SDK that isn't the latest release, please update first

**Comment by Viish** [comment] 2024-06-16 19:26
Duplicate of #2183

**Closed** 2024-06-16 19:26 UTC
