### ISSUE TITLE
Registration storm after call termination with flexisip

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#552] opened 2019-04-05 10:14 UTC
After receiving a call from flexisip (push-proxying for Asterisk) and terminating it, linphone goes into a registration storm with flexisip.

Here's a [log](http://brian.interlinx.bc.ca/linphone-registration-storm.txt) of it.

**Comment by Viish** [comment] 2019-04-05 12:14
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/531

**Closed by Viish** 2019-04-05 12:14 UTC

**Comment by brianjmurrell** [comment] 2019-04-05 12:59
Are you sure?  This storm typically only lasts a short while while the activity loop in #531 can go on for hours and hours.
