### ISSUE TITLE
Call packet loss sometime

### ISSUE THREAD

**Issue by jybin88** [BelledonneCommunications/linphone-android#2023] opened 2023-11-06 01:43 UTC
First of all, please say "Hi" or "Hello", it doesn't cost much.

1. **Describe the bug** (mandatory)
I use linphone-sdk-android-5.2.103 aar，when make a call，sometime it packet loss,  they can't hear me

2. **To Reproduce** (mandatory)

Packets are lost during normal calls

3. **Expected behavior** (mandatory)

Normal calls do not lose packets

4. **Please complete the following information** (mandatory)

 - Device:FRD-AL10
 - OS: Android 8.0
 - Version of the SDK 5.2.103
 - 
5. **Adb logcat logs** (mandatory if native crash)

[sip日志.txt](https://github.com/BelledonneCommunications/linphone-android/files/13261706/sip.txt)

**Comment by Viish** [comment] 2023-11-06 08:10
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/353

**Closed by Viish** 2023-11-06 08:10 UTC
