### ISSUE TITLE
 Call terminate without Ring continue.

### ISSUE THREAD

**Issue by AKC-Kang** [BelledonneCommunications/linphone-android#2186] opened 2024-06-18 01:38 UTC
https://github.com/BelledonneCommunications/linphone-android/assets/173016720/e2d716ee-daf8-4c52-a036-f5106c44a1e1

Please, help me

-Os: Android 10
-version : org.linphone:linphone-sdk-android:5.0+
-use method : "call.terminate();"

Normal
 (client) call click -> (Phone) Ring -> (Phone) receive call -> (client) API: call.Terminate() => Call terminate 
 
UnNormal
 (client) call click -> (Phone) Ring -> (Phone) Don't receive call -> (client) API Send: call.Terminate() => Call terminate but Ring continue
 
Sometimes when pressing the call button on the client side, users escape.
Is it possible to automatically hang up the call?"
I want to make the call hang up 3 seconds after pressing the call button. Currently, the call gets disconnected on the client side, but not on the recipient's phone.
The recipient's phone keeps ringing, and it only stops when they pick up the receiver.

Do I need to check at the settings on phone to stop ringing?

tq.

**Comment by Viish** [comment] 2024-06-18 07:25
Hi,

First of all, please update your SDK to latest version (5.3 at the time).
That being said, it looks like you're using UDP as transport protocol and that BYE message is lost, but I can't confirm that without debug logs.

Cheers,

**Comment by AKC-Kang** [comment] 2024-06-18 07:48
The Issue occurs even in the latest released app. 
and i use TCP protocol. What log files do you need? tell me how

**Comment by Viish** [comment] 2024-06-18 09:25
> What log files do you need? tell me how

@AKC-Kang If you'd followed the github template for reporting an issue you would have seen the instructions.
It's also available in our README: url=https://flexisip-staging-master.linphone.org/api

**Comment by AKC-Kang** [comment] 2024-06-19 01:22
attach log file :  https://www.linphone.org:444//tmp/6672289bd5ea2_f27a3a0112e7bb0c3325.gz

It's a very important issue for us. Please check

**Comment by Viish** [comment] 2024-06-19 07:40
Indeed the 401 isn't answered by our SDK, but I don't know why.
Could you reproduce the issue using our latest release (5.2.5) and a stable SDK (5.3.X) instead of alpha versions please?

**Comment by AKC-Kang** [comment] 2024-06-19 07:57
Tested by 
 Linphone Android 5.2.5
 Linphone SDK 5.3.47

log :  https://www.linphone.org:444//tmp/66728cd2a6a17_aa6bc674cfa49d8b2468.gz

Additionally, the same issue occurs in the Windows version.
Could it be a problem with the "office sip server" we use?

**Comment by Viish** [comment] 2024-06-19 08:19
> Could it be a problem with the "office sip server" we use?

Yes, it is likely an incompatibility at some level between your SIP server and our SIP stack.

I recommend you to contact the company I work for (Belledonne communications) using the contact form on our website https://linphone.org/contact#content-bottom3 to request a quotation for either a support or dev-assist contract to help you with that.

Cheers,

**Comment by AKC-Kang** [comment] 2024-06-20 00:58
Will there be any costs to solve this problem?
this issue very import to us.

**Comment by Viish** [comment] 2024-07-01 08:06
As mentioned above, this is out-of-scope of github help we can provide, so I'm closing this issue.

**Closed by Viish** 2024-07-01 08:06 UTC
Labels: status: feedback
