### ISSUE TITLE
Server Certificate and client certificate for authentication

### ISSUE THREAD

**Issue by renukaghate** [BelledonneCommunications/linphone-android#1415] opened 2021-06-03 10:58 UTC
in the linphone android code where is the server certificate to be located. 
and if the linphone android, if the  client is to be authenticated using client certificate then where it has to be placed.

**Comment by Viish** [comment] 2021-06-14 08:53
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1418

**Closed by Viish** 2021-06-14 08:53 UTC
