### ISSUE TITLE
unexpected video

### ISSUE THREAD

**Issue by judklaus** [BelledonneCommunications/linphone-android#1421] opened 2021-06-10 07:31 UTC
Hi @Viish, I just saw that when I have two Linphone apps with the same following video settings, I pause the audio call and resume it back, videos on both sides are initiated. The logs are also below.

Enable video = true
Initiate video calls = false
accept incoming video requests = true

Log of the callee and also the one that pause/resumes
https://www.linphone.org:444//tmp/60c1b1d6ed835_31d3f916e86c47a924c5.gz

Log of the caller
https://www.linphone.org:444//tmp/60c1b1b650eab_3f3560f3e02858082e88.gz

Best regards.

**Comment by judklaus** [comment] 2021-06-10 08:22
@Viish this returns true even though it should be false

boolean videoEnabled =
                KarelPreferences.instance().isVideoEnabled()
                        && call != null
                        && call.getCurrentParams().videoEnabled();

**Comment by judklaus** [comment] 2021-06-10 08:23
@Viish This returns true. It should be false.

private void updateInterfaceDependingOnVideo()

boolean videoEnabled =
                LinphonePreferences.instance().isVideoEnabled()
                        && call != null
                        && call.getCurrentParams().videoEnabled();

**Comment by judklaus** [comment] 2021-06-10 14:13
@Viish By the way, it only happens when the callee pauses/resumes the call. If the caller pauses/resumes, no problem, the video is not initiated.

**Comment by Viish** [comment] 2021-06-14 08:40
Hi,
Can you reproduce the issue using the beta on the Play Store?
Thanks in advance.

**Comment by judklaus** [comment] 2021-06-14 10:46
Hi @Viish I'm trying to join the beta testing however it is not responding. Which version on GitHub is the beta version? Is it the release 4.5?

**Comment by Viish** [comment] 2021-06-14 11:15
Yes it is the release/4.5 branch of linphone-android repository.

**Comment by judklaus** [comment] 2021-06-14 11:36
@Viish I can reproduce the issue with the beta version as well.

Log of the caller: https://www.linphone.org:444//tmp/60c73db6b3236_5c97520fbacea4afcee5.gz 
Log of the callee/pauser: https://www.linphone.org:444//tmp/60c73de504467_8caa6473b173dc050332.gz

**Comment by Viish** [comment] 2021-06-14 11:48
Thanks. We'll fix it.

**Comment by judklaus** [comment] 2021-06-15 08:39
Hi @Viish, is it an error in linphone-android/src or linphone-sdk?

**Comment by Viish** [comment] 2021-06-15 08:40
I believe the issue is in linphone-sdk.

**Comment by Viish** [comment] 2021-06-17 13:26
Fixed in linphone-sdk:
```
commit 1f66b32a638267048798110300aedcada7d6c74f
Author: Andrea Gianarda <andrea.gianarda@belledonne-communications.com>
Date:   Tue Jun 8 09:32:37 2021 +0200

    Do not add video stream when callee pauses a call if video is automatically accepted
```

**Closed by Viish** 2021-06-17 13:26 UTC
Labels: type: bug
