### ISSUE TITLE
Outgoing SMS receives 415 Unsupported Media Type: How disable "cpim_in_basic_chat_rooms_enabled"

### ISSUE THREAD

**Issue by aGrimRepoMan** [BelledonneCommunications/linphone-android#2147] opened 2024-04-18 23:47 UTC
Hello, I hope you are doing well.

**Problem Description**
Using Linphone Android chat capability with VoIP.ms, I can receive SMS, but sending SMS always fails.  

TL;DR: The Voip.ms SMS service seemingly doesn't support receiving SIP MESSAGE method with content-type header = “message/cpim”. It replies with a 415 “Unsupported Media Type” response and Linphone Android then marks the SMS (chat) message as failed.

I discovered a configuration option on Linphone Desktop called “cpim_in_basic_chat_rooms_enabled”. When I set that to 0 in linphonerc to disable CPIM (RFC 3862) behaviour, I can send SMS messages via voip.ms with no issues. 

I then confirmed via “view config” that my Linphone Android app indeed has cpim_in_basic_chat_rooms_enabled=1.  I can’t find how to set it to 0 via the UI. How can I disable CPIM in basic chat rooms, without building the android app myself?

Thanks in advance for considering this.

**To Reproduce**
Starting conditions: Linphone android app open & registered with VoIP.ms.
a. Click on desired contact, then click on chat icon to display contact’s cell phone number
b. Type desired text message, tap send icon.
c. Shortly after, a small red exclamation mark shows up against the text message’s bubble, indicating message delivery failure. The recipient never receives the message.

**Expected behaviour**
Steps a & b as above. 
Step c should result in the SMS being delivered to the recipient.

**Version information**
 - Device: Xiaomi Redmi Note 5
 - OS: Android 9
 - App Version: 5.2.3
 - SDK Version: 5.3.19
 - App Origin: F-Droid
 - Android details: stock MIUI Global 12.0.2, *not* rooted.

**SDK logs**
Relevant logs attached. 
[Aside: As seen in the logs, the MESSAGE method with "Content-Type: application/im-iscomposing+xml" also receives 415 error from voip.ms, but that is not what is causing the SMS failure (confirmed via Linphone desktop config file experimentation). In this issue, I’m only concerned with how to configure Linphone Android to send the actual SMS message using "content-type: plain/text" instead of "Content-Type: message/cpim".

[redacted CPIM logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/15031460/redacted.CPIM.logs.txt)

**Comment by Viish** [comment] 2024-04-19 07:23
Duplicate of https://github.com/BelledonneCommunications/liblinphone/issues/137

**Closed by Viish** 2024-04-19 07:23 UTC

**Comment by aGrimRepoMan** [comment] 2024-04-19 13:31
Hi Vish,

Thanks for your response.

[https://github.com/BelledonneCommunications/liblinphone/issues/137](url) is a different issue. It deals with the typing indicator message (has "Content-Type: application/im-iscomposing+xml"). Although I do see that problem with my SIP service provider, it does not impact my main concern, which is the success or failure of the SMS message itself (which is sent later, after the "isComposing" message, i.e. once user finishes typing their text and taps the send button).

What I'm asking in *this* issue (2147) is how to configure Linphone-Android to not use SIP MESSAGE method with content-type header = “message/cpim” when sending the chat (SMS) message to a server that only supports "Content-Type: plain/text".  See the MESSAGE method with call-id = cI0mvDIAA4 in the trace file.  

On Linphone-Desktop, I achieve that by changing the _linphonerc_ config parm "cpim_in_basic_chat_rooms_enabled" from 1 to 0, but I haven't found a way to do that from the android app's UI. Is there any way? If not, could it be created in a future release (feature request) to allow users to control whether RFC 3862 CPIM or plain text is used? Note that I don't build my own app, I download from F-Droid.

Thanks again for considering this.

**Comment by Viish** [comment] 2024-04-19 13:34
HI @aGrimRepoMan,

No, it's not currently possible to change that setting through the UI at the moment.
However you can alter the configuration like you did on desktop using [remote provisioning](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/).

Cheers,

**Comment by Viish** [comment] 2024-04-19 13:43
FYI, there will be a UI setting for that in 6.0 release of Linphone Android.

**Comment by Viish** [comment] 2024-04-19 15:15
No, I guess there was a mistake at some point.
There is two files "linphone_default_values" and a "default_values" that contains default settings for accounts, and CPIM is only enabled in the "linphone_default_values" file, but some bug must have loaded it instead of the other and causing your account to have it enabled when it shouldn't have...
