### ISSUE TITLE
Could NOT find SpanDSP While build Linphone SDK

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1507] opened 2021-09-20 05:58 UTC
Hey, can you please help me to solve this error

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SpanDSP (missing: SPANDSP_INCLUDE_DIRS SPANDSP_LIBRARIES
  HAVE_SPANDSP_H)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSpanDSP.cmake:43 (find_package_handle_standard_args)
  CMakeLists.txt:186 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ravi/LinphoneSDK/demo/build/WORK/android-arm64/Build/ms2/CMakeFiles/CMakeOutput.log".
make[5]: *** [CMakeFiles/EP_ms2.dir/build.make:121: /home/ravi/LinphoneSDK/demo/build/WORK/android-arm64/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[4]: *** [CMakeFiles/Makefile2:1070: CMakeFiles/EP_ms2.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
make[2]: *** [CMakeFiles/android-arm64.dir/build.make:114: android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/android-arm64.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by Viish** [comment] 2021-09-20 06:05
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/102

**Closed by Viish** 2021-09-20 06:05 UTC
