### ISSUE TITLE
unable to switch to bluetooth

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#841] opened 2019-11-21 22:23 UTC
https://sergio.outerface.net/misc/ScreenRecord-2019-11-22-01-18-50.mp4

Native android dialer works fine and routes audio to bt headset.

**Comment by Viish** [comment] 2019-11-22 08:57
Can you please send logs ?
Also is it related to #842 ?

**Comment by 532910** [comment] 2019-11-22 11:58
Would you like to say you didn't receive a letter with the subject: issue #841 linphone1.log or do you need a logcat?

**Comment by 532910** [comment] 2019-11-22 11:59
It's not related to #842.

**Comment by Viish** [comment] 2019-11-22 15:19
Does your BT headset supports SCO ?

**Comment by Viish** [comment] 2019-11-22 15:29
Can you try with another audio codec like Speex or PCMU/PCMA ?

**Comment by 532910** [comment] 2019-11-22 15:35
Sorry, forgot to say, it's working configuration, this headset (PLT Edge) and codec. It happens sometimes, and restarting Linphone fixes it.

**Comment by Viish** [comment] 2019-11-22 15:51
Ok I close it.

**Closed by Viish** 2019-11-22 15:51 UTC

**Comment by 532910** [comment] 2019-11-30 07:43
Why so?

**Comment by 532910** [comment] 2019-12-02 11:29
Sylvain, could you explain, why do you close it?
I can't reproduce this issue, but I captured a log that I sent you.

**Comment by Viish** [comment] 2019-12-02 11:56
As you just said it, you can't reproduce the issue and neither am I.
The logs you sent simply show a failure on Android to correctly route the audio to the headset, nothing more that I can do on my side (the code already makes 10 attemps to be sure, and in your case none works).

**Comment by 532910** [comment] 2019-12-04 03:51
OK, it's clear. But I see this issue occasionally. How should I capture or investigate it next time I'll see this issue?

**Comment by Viish** [comment] 2019-12-04 08:57
Send adb logcat logs, maybe there will be a system log that will help understand the issue.
