### ISSUE TITLE
Speaker Stop working for the Conference Initiator

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1382] opened 2021-05-02 22:34 UTC
Hi @Viish ,

App user, who add other party in audio conference, experiencing speaker misbehave. Let say **A** call **B** and **B** again call **C**. **B** and **C** is talking and **A** is on hold. All 3 party having there speaker on and audio also routed through their speaker only. everything working fine till this point. But as soon as **B** press  **'Add in Conference'** button, The audio at **B** start coming from Earpiece no matter **B** toggle speaker off/On. The other Party i.e. **A** and **C** able to listen Audio conference on Speaker Mode.

Logs has been attached.

[AudioConf_Inititator_SpeakeNotWorking.txt](https://github.com/BelledonneCommunications/linphone-android/files/6412371/AudioConf_Inititator_SpeakeNotWorking.txt)

**Comment by Viish** [comment] 2021-05-03 06:44
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1346

**Closed by Viish** 2021-05-03 06:44 UTC
