### ISSUE TITLE
Incoming messages "From" header issues

### ISSUE THREAD

**Issue by osering** [BelledonneCommunications/linphone-android#1913] opened 2023-05-09 11:58 UTC
Some messaging issues were identified:

1) Linphone always cuts off domain part of "From" header (sender);

2) When, according to RFC3261 (SIP), Section 20.20 "From", which refers to Section 20.10 "Contact", URI is "extended" like this
From: "dongle1 aāuū" \<sip:ussd-1@olo-tst>, there is problem.

a) when "sip:" is skipped, it looks OK.
![linp1](https://github.com/BelledonneCommunications/linphone-android/assets/62410690/4f622dda-51e9-4082-9556-eb5dc457d278)

b) when "sip:" is NOT skipped, it cuts off contact and shows protocol "sip:" which in sip client software seems to be not necessary.
![linp2](https://github.com/BelledonneCommunications/linphone-android/assets/62410690/f791ae03-7023-462f-8e05-023361a8a9d7)

3) Message disappears (do not arrive) when there is "@" in the "From" header URI (put by Asterisk, for example)

4) "From" header in messages list is always **duplicated**.
It shows up both - in messages' bigger font first (sender) line (where it should be) and as the beginning of the message body, separated with ":" from message body.
Instead, this space there could be good place to show arrival time

P.S. Thanks for great SIP client for free OSes: Linux (including, Ubuntu Touch) and Android!

**Comment by Viish** [comment] 2023-05-09 12:17
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1911

**Closed by Viish** 2023-05-09 12:17 UTC
