### ISSUE TITLE
Unable to detect OPTIONS SIP message sent from VOIP server

### ISSUE THREAD

**Issue by athirarenjan** [BelledonneCommunications/linphone-android#1490] opened 2021-09-01 05:51 UTC
Unable to detect OPTIONS SIP message sent from VOIP server

I would like to detect OPTIONS SIP message being sent from Asterisk server to my android application which uses linphone library. By detecting OPTIONS SIP message at regular interval from VOIP server, I need to decide if the VOIP server is available or not available.In linphone android application, we have a status "Online", "Not connected", "Connection in progress", etc. So there should be some way to detect if the voip server is available or not available 

Which callback needs to used?
I am using 4.4.3 linphone-sdk version.
i tried using almost all the call backs given by the library...but nothing worked.
for example i tried using 
1)
`@Override
            public void onMessageReceivedUnableDecrypt(Core lc, ChatRoom room, ChatMessage message) {
                super.onMessageReceivedUnableDecrypt(lc, room, message);
            }`
2) `@Override
            public void onMessageReceived(Core lc, ChatRoom room, ChatMessage message) {
                super.onMessageReceived(lc, room, message);
            }`

I don't find any callback returning OPTIONS Message.

**Comment by Viish** [comment] 2021-09-01 07:18
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/174

**Closed by Viish** 2021-09-01 07:18 UTC
