### ISSUE TITLE
SMS chats missing from summary

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#766] opened 2019-09-10 14:03 UTC
Updating from release/4.1 to master, when I open the chat tab, I am no longer seeing all of the chats that were there before the upgrade.

Additionally, when I receive an SMS from a given number, I get a head's up notification for it but the message tab doesn't show any indication of the new message.  I can press the head's up notification and it opens the chat for that number.  From there there are two problems:

1. Replying fails and produces a little white _x_ in a red round circle to the bottom right of the reply.
1. When I use the "back arrow" at the top of the chat to go back to the summary, the chat is missing from the summary.

The [log](http://brian.interlinx.bc.ca/linphone-failed-sms-reply.txt).

**Comment by Viish** [comment] 2019-09-10 16:11
Can you add logs from where the app starts please ?

**Comment by Viish** [comment] 2019-09-10 16:11
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/765

**Comment by brianjmurrell** [comment] 2019-09-10 19:12
> Can you add logs from where the app starts please ?

[Log](http://brian.interlinx.bc.ca/linphone-failed-sms-reply2.txt).

**Comment by brianjmurrell** [comment] 2019-09-11 10:55
So what's the path forward now?  This is clearly not just a one-off case.  #765

**Comment by 532910** [comment] 2019-09-19 08:00
Looks like I've the same issue:
There are no messages at all displayed in messages list:
![image](https://user-images.githubusercontent.com/14617699/65224368-b5832d80-dacb-11e9-933d-eb71230811df.png)
But when I press send a message to a contact I see the thread:
![image](https://user-images.githubusercontent.com/14617699/65224726-6ab5e580-dacc-11e9-8da5-709578f3b789.png)
![image](https://user-images.githubusercontent.com/14617699/65224856-b1a3db00-dacc-11e9-9432-19ab0d281997.png)
![image](https://user-images.githubusercontent.com/14617699/65224863-b49ecb80-dacc-11e9-92ed-29ceadeccc8a.png)

**Comment by Viish** [comment] 2019-09-19 08:02
Sergio, what version do you have (app and SDK please) ?

**Comment by 532910** [comment] 2019-09-19 08:06
4.1-126-gfc4baf41 / 4.2-138-g0cea898
and the previous one from GPlay beta channel.

**Closed** 2019-09-19 09:08 UTC
Labels: type: bug
