### ISSUE TITLE
How to add mobile TLS file?

### ISSUE THREAD

**Issue by sercan447** [BelledonneCommunications/linphone-android#1747] opened 2022-08-16 09:58 UTC
I have a .pem and .key file that I put in the flexisip server.
At the same time, I put the .pem file in the mobile source code.

in linphone mobile source code
I added it as "res/raw/file.pem".
later on
I created network_security_config.xml file.

**</?xml version="1.0" encoding="utf-8"?/>
</network-security-config>
</domain-config/>
    </domain includeSubdomains="true"/>www.domain.com</domain/>
    </trust-anchors/>
        </certificates src="@raw/file" />
    </trust-anchors/>
</domain-config/>
</network-security-config/>**

I wrote the code as

Is this enough for me?
do i need to do anything else?

**Comment by Viish** [comment] 2022-08-16 10:01
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1746

**Closed by Viish** 2022-08-16 10:01 UTC
