### ISSUE TITLE
Linphone irreversibly locks screen (via proximity sensor) upon connection, locking me out of phone

### ISSUE THREAD

**Issue by afcady** [BelledonneCommunications/linphone-android#1403] opened 2021-05-18 22:17 UTC
Seems to be a known issue on the Nexus 5:

> On Fri, Mar 18, 2016 at 1:41 PM, Stefan Monnier <address@hidden> wrote:

    When I use Linphone on my Android tablet, during the call, I see a normal
    Linphone screen with buttons to hang up and do various other things.

    But when I use it on my Android phone, as soon as I hit the button to
    make a call, the screen goes black and I can't figure out how to get
    back to Linphone's controls (neither the "back" nor the "menu" buttons
    (nor the power button) have any visible effect, I end up having to use
    the home button to get back to a normal screen from where I can get to
    the tools to kill Linphone).

> https://lists.gnu.org/archive/html/linphone-users/2016-03/msg00064.html

However, unlike that user, I have not figured out a way to get screen to turn back on, other than disconnecting the call from the other end.

**Comment by afcady** [comment] 2021-05-19 18:24
I forgot to say that this only happens when video is off.

If I disable video sending on the other side completely, it happens instantly on connect.

If video sending is enabled on the other side, it happens instantly when video is disabled from linphone UI.




Re: logs.  I uploaded logs and looked at them.  They contain some private information such as IP addresses so I didn't put it here in plaintext.  I suppose, if you want to put a public key here, I will upload it encrypted with that.

**Comment by afcady** [comment] 2021-05-20 08:14
Done.

**Comment by Viish** [comment] 2021-05-20 08:29
You are using an old version of linphone-android (4.3.1).
Latest release is 4.4.x and you should test with 4.5.0-beta.

Anyway there are a lot of crashes in callbacks (but they aren't visible in our logs, you should check your adb logcat logs).
Also for some reason your device's screen is turned off immediatly after CallActivity is started...

**Comment by afcady** [comment] 2021-05-20 11:40
I was able to replicate the bug with 4.4.3 from https://f-droid.org/repo/org.linphone_4403.apk

I also tried installing http://web.linphone.org/releases/android/linphone-android-4.4.2.apk which failed to install.

Is there any apk for 4.5.0-beta?

**Comment by afcady** [comment] 2021-05-20 11:41
Also, I emailed logs from that newer one, though not the adb.

**Comment by Viish** [comment] 2021-05-20 11:55
> Is there any apk for 4.5.0-beta?

http://linphone.org/snapshots/android/linphone-android-4.5.0-beta.11+3ee0a986a.apk

**Comment by Viish** [comment] 2021-05-20 11:58
And you still have issues that can't be fixed without adb stacktrace:
```
2021-05-18 17:50:36:171 [/liblinphone] ERROR Listener 0x100a7f raised an exception
2021-05-18 17:50:36:172 [/liblinphone] ERROR Listener 0x200983 raised an exception
```

**Comment by afcady** [comment] 2021-05-20 15:20
Sadly, linphone-android-4.5.0-beta.11+3ee0a986a.apk  also failed to install.  It probably has to do with difference in the build environment between your build server and Fdroid.org's, which of course, is unrelated to #1403.

I will email you the adb log from the 4.4.3 version, shortly, (I still must get up find cable etc.)

**Comment by afcady** [comment] 2021-05-21 13:44
Did you receive & have a chance to look at those logs?  Any news?  Thanks.

**Comment by Viish** [comment] 2021-05-21 14:02
Yes, and the logs aren't helpful as there is no stack trace of the crashes I was looking for, nor any explanation on why your screen is turned off when the call starts.
Do you reproduce the issue on another device?

**Comment by afcady** [comment] 2021-05-26 18:19
I tried on two other Nexus 5 computers.  Unfortunately, neither could replicate the bug. 

In the one case, there was no bug at all!  Linphone was fully functional (at least @ 4.4.3).  But note: that was a different hardware model of Nexus 5.  So not necessarily an informative test.

On the other Nexus 5, which is AFAIK identical hardware to the one that replicates the bug, I could not even get linphone to connect a call so I could not test for the proximity sensor behavior.  A difference here is that that phone runs LineageOS while the others run stock Android.

By the way, that was all only using the older apk.  The 4.5 beta did not install successfully on any Nexus 5. 

I also tried a Nexus 5X which could both install 4.5 and work with full functionality.  But that's not the same hardware at all.

-----

The screen was definitely not actually turned off when the call started, by the way.  I started the call using the linphone UI on the screen.

**Comment by Viish** [comment] 2021-05-26 18:34
> The screen was definitely not actually turned off when the call started, by the way. I started the call using the linphone UI on the screen.

That's weird, there are way too many logs like that one in the file you sent me:
`[Platform Helper] Device is not in interactive mode (screen is OFF)`

As you can't reproduce the issue (and neither can I), I'm closing this.

**Comment by afcady** [comment] 2021-05-26 18:34
OK, after I wrote that (but before I submitted it) I went to reproduce the issue with the original phone and, even though the issue replicated perfectly reliably every single time in the past, this time it also worked _sometimes_.  Maybe about 50/50.  And when it failed, it flashed the post-video screen for a split second that didn't seem to happen before.

I can upload a video of this behavior.  All I need to do to reproduce is make call and turn camera off and on until screen goes dead.  Then hang up the other end to make the screen go live, and repeat.

I have a random idea that isn't based on even looking at the code that maybe the proximity sensor because of actual hardware problem flickers from 0 to 1 to 0 real quick when turned on and maybe the second 0 gets dropped by the software that controls the screen for some reason related to the quickness.  Received out of order?

**Closed by Viish** 2021-05-26 18:34 UTC

**Comment by Viish** [comment] 2021-05-26 18:42
That's a possibility but that's hard to proove.

**Comment by afcady** [comment] 2021-05-26 18:43
A workaround with no debugging is maybe put an option to just ignore the proximity sensor in linphone.

**Comment by Viish** [comment] 2021-05-26 18:44
Sorry but I won't add a setting for an issue we never saw before, that even yourself have trouble to reproduce and that happens on only some devices from a specfic model that is quite old.

**Comment by afcady** [comment] 2021-05-26 18:45
I don't have trouble to reproduce it.  It definitely makes linphone completely unusable on the phone.

**Comment by Viish** [comment] 2021-05-26 18:47
Feel free to build your own version of the project with either the setting or the proximity sensor disabled.
It's also possible issue will be fixed with 4.5 release...

**Comment by afcady** [comment] 2021-05-26 19:13
Well before that I am going to try to find the bug in the source.

By the way.  The older phones are much cheaper and the barrier to entry to use VOIP with linphone is much lower with them.  And they're less likely to have active phone service so that linphone adds much more value to them.  You can get many more users out of the same investment of money (by them) if they are using the older phones.  The users with the newest phones regularly shed older phones onto the used market.  There are going to be more of these old used phones out there than the new ones.  Linphone's potential for the world is to give a higher portion of the world access to real time voice communications; a part of fully realizing that potential is workarounds for all of Android's massive portability problems.  So I hope you are not dismissing all such concerns as a matter of policy.  Android is like 1980s Unix, not portable, needs lots and lots of ifdefs, so to speak.

**Comment by afcady** [comment] 2021-05-30 17:40
> Feel free to build your own version of the project with either the setting or the proximity sensor disabled.

Can you explain more what you mean by this?

This whole exchange left me much less motivated to fix the issue than I was at the beginning, because (1) you closed the issue and (2) you didn't seem to acknowledge the problem or that it's reproducible.

Thus I wonder if I were able to fix it, would my fix even be incorporated?

**Comment by afcady** [comment] 2021-05-30 17:42
And, when you say you won't add a setting to disable the proximity sensor, do you mean that you won't write the source code or that you won't accept it?

Adding the setting wouldn't be worth it if I then had to get into the business of distributing linphone just to share my work with other people.

**Comment by Viish** [comment] 2021-05-31 07:47
> Can you explain more what you mean by this?

Yes. The project is open-source, so it's quite easy for you to disable the feature that causes you troubles, build the app and deploy it on your device.

> you didn't seem to acknowledge the problem or that it's reproducible.

You can only reproduce it on 1 device, not even all devices of the same model. Furthermore you didn't even tried with our latest version that maybe doesn't have the issue. So yes issue is closed unless somehow this issue still exists on our latest version and is reproducible on more than one device.

> Thus I wonder if I were able to fix it, would my fix even be incorporated?

No. The fix itself is easy: disabling the proximity sensor. If I wanted to to include it upstream I'll do it myself.
