### ISSUE TITLE
Video Call showing frozen image

### ISSUE THREAD

**Issue by nick2601** [BelledonneCommunications/linphone-android#1409] opened 2021-05-24 10:36 UTC
Hi @Viish ,
I have created a custom Sip Invite for the Video call, the call is being established, but unfortunately there is no exchange of video frames and a  frozen image appears on both of my devices.
Also when I enable AVPF , my app crashed.
I have added the logs for the same.
Thank you in advance..
[videoCall.txt](https://github.com/BelledonneCommunications/linphone-android/files/6531696/videoCall.txt)

**Comment by Viish** [comment] 2021-05-24 11:38
Hi,
Most probably a network issue sa some packets are received but clearly you have a huge loss rate (5245 packets sent for audio, 26 received and for video 26597 sent for 2036 received).
What's your crash with AVPF?

**Comment by nick2601** [comment] 2021-05-27 12:15
> Hi,
> What's your crash with AVPF?
I am getting a this error 
2021-05-27 17:42:55.294 8752-8767/org.linphone.debug A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1800000010 in tid 8767 (FinalizerDaemon), pid 8752 (.linphone.debug)

**Comment by Viish** [comment] 2021-05-27 12:16
Please a full stack trace with symbols and debugs logs from before it happens...

**Comment by nick2601** [comment] 2021-05-27 12:21
> Please a full stack trace with symbols and debugs logs from before it happens...

I have added the full stacktrace above..

**Comment by Viish** [comment] 2021-05-27 12:28
> I have added the full stacktrace above..

Where? the SIGSEGV line isn't a stack trace...

**Comment by nick2601** [comment] 2021-05-27 12:31
> > I have added the full stacktrace above..
> 
> Where? the SIGSEGV line isn't a stack trace...

Hi @Viish , can you compare with timestamp and check you will get for sure

**Comment by Viish** [comment] 2021-05-27 12:46
There is no stack trace in the debug logs of our SDK because the SDK crashed (it can't capture it's own crashes...)
Stack trace is in adb logcat output only.

**Comment by nick2601** [comment] 2021-06-01 09:35
> There is no stack trace in the debug logs of our SDK because the SDK crashed (it can't capture it's own crashes...)
> Stack trace is in adb logcat output only.

Following are the errors I observed due to which my app crashed..
[60b5fe6a8916c_0d292e5ae84539b58741.gz](https://github.com/BelledonneCommunications/linphone-android/files/6575156/60b5fe6a8916c_0d292e5ae84539b58741.gz)

2021-06-01 14:58:25.182 20422-20437/org.linphone.debug E/Linphone: Object [0x75a3e0a170] freed twice or corrupted !
2021-06-01 14:58:25.182 20422-20437/org.linphone.debug E/Linphone: Object type might be [LinphoneVideoActivationPolicy]
2021-06-01 14:58:25.182 20422-20437/org.linphone.debug A/Linphone: Fatal object error encountered, aborting.
2021-06-01 14:58:25.183 20422-20437/org.linphone.debug A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20437 (FinalizerDaemon), pid 20422 (.linphone.debug)

**Comment by Viish** [comment] 2021-06-01 12:25
Still no stack trace and for a different issue (that I don't reproduce)...

Please attach what I ask for or I'll close the issue...
Also make sure to use latest release (for both the app and SDK)

**Comment by nick2601** [comment] 2021-06-03 04:34
> Still no stack trace and for a different issue (that I don't reproduce)...
> 
> Please attach what I ask for or I'll close the issue...
> Also make sure to use latest release (for both the app and SDK)


Hi @Viish ,
Thanks for the reply,we are planning to migrate to Kotlin release as soon as possible.
I am adding two logs:
The first one is adblogcat output.
The second is Linphone SDK logs.
[adbLogcatTrace.txt](https://github.com/BelledonneCommunications/linphone-android/files/6588938/adbLogcatTrace.txt)
[SDKLogs.gz](https://github.com/BelledonneCommunications/linphone-android/files/6588945/SDKLogs.gz)
Thank you for the help in advance

**Comment by nick2601** [comment] 2021-06-07 05:58
Hi @Viish,
Any updates on the issue..

**Comment by Viish** [comment] 2021-06-15 19:55
Crash related to payload types has been fixed in linphone-sdk master branch, and fix will be backported to release/4.5 tomorrow.

**Closed by Viish** 2021-06-15 19:55 UTC
