### ISSUE TITLE
terminating the app after incoming call is not working

### ISSUE THREAD

**Issue by shubhamparekh2000** [BelledonneCommunications/linphone-android#2159] opened 2024-05-07 10:56 UTC
I'm using the push kit,
when my app is terminated state incoming call notification time my app will not awake can you please explain to me how to resolve this issue

push kit notification will not be working

**Comment by Viish** [comment] 2024-05-07 11:22
Duplicate of https://github.com/BelledonneCommunications/linphone-iphone/issues/932 and has nothing to do with Android

**Closed by Viish** 2024-05-07 11:22 UTC
