### ISSUE TITLE
All the text messages are failing

### ISSUE THREAD

**Issue by demanuel** [BelledonneCommunications/linphone-android#1277] opened 2021-01-19 08:58 UTC
Please check the image attached:

![Screenshot_20210119-090851_Linphone](https://user-images.githubusercontent.com/1687786/105010633-e2cf4b00-5a33-11eb-893a-2a6d9488f9eb.png)

I have the following linphone from f-droid

```
Linphone Android 4.3.1 (release)
Linphone SDK 4.4.2 (tags/4.4.2^0)
```

Don't know if this has any impact, but i have lineageOS (android 10) without gapps/microg (google services).

**Comment by Viish** [comment] 2021-01-19 09:02
Please provide SDK logs showing the issue.

**Comment by demanuel** [comment] 2021-01-19 21:43
The logs are in https://www.linphone.org:444//tmp/6006a187584c9_43b2577165bb0a8a5fd9.gz

The logs on the time of the last message exchange contains:

```
2021-01-17 09:05:11:558 [org.linphone/belle-sip] ERROR stream connect failed Network is unreachable
2021-01-17 09:05:11:558 [org.linphone/belle-sip] ERROR Cannot connect to [TLS://lime.linphone.org:443]
2021-01-17 09:36:35:251 [org.linphone/liblinphone] ERROR Couldn't send chat room list subscription because there's no conference factory uri
2021-01-17 09:36:35:416 [org.linphone/belle-sip] ERROR stream connect failed Network is unreachable
2021-01-17 09:36:35:416 [org.linphone/belle-sip] ERROR Cannot connect to [TLS://lime.linphone.org:443]
2021-01-17 10:05:16:422 [org.linphone/belle-sip] ERROR stream connect failed Network is unreachable
2021-01-17 10:05:16:422 [org.linphone/belle-sip] ERROR Cannot connect to [TLS://sip.linphone.org:5223]
2021-01-17 10:05:16:928 [org.linphone/liblinphone] ERROR Couldn't send chat room list subscription because there's no conference factory uri
2021-01-17 10:05:16:949 [org.linphone/belle-sip] ERROR stream connect failed Network is unreachable
2021-01-17 10:05:16:949 [org.linphone/belle-sip] ERROR Cannot connect to [TLS://lime.linphone.org:443]
2021-01-17 10:08:53:396 [org.linphone/liblinphone] ERROR Couldn't send chat room list subscription because there's no conference factory uri
2021-01-17 10:10:05:102 [org.linphone/belle-sip] ERROR stream connect failed Network is unreachable
2021-01-17 10:10:05:102 [org.linphone/belle-sip] ERROR Cannot connect to [TLS://sip.linphone.org:5223]
2021-01-17 10:10:05:120 [org.linphone/linphone-android] ERROR [Linphone Contact] Firstname and lastname are both null !
2021-01-17 10:10:05:786 [org.linphone/belle-sip] ERROR stream connect failed Network is unreachable
2021-01-17 10:10:05:786 [org.linphone/belle-sip] ERROR Cannot connect to [TLS://lime.linphone.org:443]
```

However this isn't true. I always had internet connection as i was at home all day (sunday). And it wouldn't explain how i got a message.

This seems to happen when i leave the app in background. Usually this is fixed, by exit the app via menu, close it, and then starting the app again.

**Comment by Viish** [comment] 2021-01-20 08:30
In your logs the verbose logs are only enabled at the end, so it doesn't help.
Please clean your logs, reproduce the issue and send them again.

**Comment by demanuel** [comment] 2021-01-20 12:11
@Viish Will do. Unfortunately it may take a while as i don't have much contacts using SIP directly :-(

**Comment by demanuel** [comment] 2021-01-20 18:13
The logs can be found in: https://www.linphone.org:444//tmp/60086f4de5092_fc41d20dab7ff56656db.gz

Both LIME messages (although this can be for some other reason) and the normal ones were failing:
![User 1 lime messages linphone](https://user-images.githubusercontent.com/1687786/105216152-17cdc180-5b4a-11eb-99fd-9f31c3d65b66.png)

![User 2 normal messages ](https://user-images.githubusercontent.com/1687786/105216242-30d67280-5b4a-11eb-9a6d-f1408743905b.png)

I also tried to call a user on their linphone sip address and it failed, but if i called the antisip address it would work fine.

**Comment by demanuel** [comment] 2021-01-21 09:39
More cleaned up logs (this time only with messages. All failed!): 

https://www.linphone.org:444//tmp/60094a63b0ba2_972bf7f220f38e6ec590.gz

**Comment by Viish** [comment] 2021-01-21 09:57
It seems there is 3 issues:
For the call, it is correctly sent but the remote doesn't answer, probably the push isn't received or the device is offline etc...
For the LIME messages, there is an auth info issue where it tries to use the antisip credentials instead of sip.linphone.org one.
For the basic messages, looks like the network becomes unavailable and takes some time to notify the socket of the connection reset.
My recommendation is for you to install the 4.4 beta version from the Play Store or from our website, it will probably those issues. If not, new logs will be helpful.
Cheers,

**Comment by demanuel** [comment] 2021-01-21 17:58
Thanks for the reply

> probably the push isn't received or the device is offline etc
The PC was on with latest linphone (4.2.5 i think)  with two accounts configured. Only the sip.linphone.org account had troubles to receive the call.

> My recommendation is for you to install the 4.4 beta 
Unfortunately i don't have the google playstore installed, so when i want to install apps from there i use the aurora store, but unfortunately i don't see any option there to download a beta version. 

I guess i will have to wait until a new stable version reaches the f-droid.

**Comment by Viish** [comment] 2021-01-21 17:59
You can also download the APK directly from our website: http://linphone.org/releases/android/

**Comment by demanuel** [comment] 2021-01-21 21:41
Downloaded and installed. 

I will check if this still happens. 

To use messages (either normal or lime) do both users (receiver and sender) need to be online?

**Comment by Viish** [comment] 2021-01-21 23:19
Depends of you have push notifications enabled or not, but normally no you don't have to.

**Comment by demanuel** [comment] 2021-01-23 12:28
With the latest beta android client:

Calling from the Android client to windows client does not work (linphone account to linphone account).  Logs: https://www.linphone.org:444//tmp/600c145f83de3_59023f9f7b7ecd74af18.gz

**Comment by Viish** [comment] 2021-01-23 13:19
Can you also attach the logs from the desktop client please? Logs from Android seems fine except for the absence of answer of the remote.

**Comment by Viish** [comment] 2021-02-03 15:33
Can I close the issue?

**Comment by demanuel** [comment] 2021-02-04 06:58
Yes please, I haven't been able to reproduce it with the latest versions

A February 3, 2021 3:33:56 PM UTC, Sylvain Berfini <notifications@github.com> escreveu:
>Can I close the issue?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BelledonneCommunications/linphone-android/issues/1277#issuecomment-772598395
-- 
Sent from my phone with K-9 Mail. Please excuse my brevity.

**Closed** 2021-02-04 08:20 UTC
