### ISSUE TITLE
Chat Duplications with Local IP Address

### ISSUE THREAD

**Issue by sagarikakrify** [BelledonneCommunications/linphone-android#713] opened 2019-07-16 09:52 UTC
Hello Team,

I am using Linphone 4.1 source code .I have one issue in this .While users chatting creating Duplicates in Chat Room. One with my SIP Domain another one with Mobile IP (Local Domain).I am unable solve this issue .I have tried to set Domain while sending message and some other places in ChatMessageFragment and ChatRoomFragment but it did not work.I put log in the LinphoneManager While reciveing Message Notification Domain showing with Mobile IP Address.Please help me out of this.

Thanks in Advance

**Comment by Viish** [comment] 2019-07-17 14:51
Duplicate of #680, #605 and #627

**Closed by Viish** 2019-07-17 14:51 UTC
