### ISSUE TITLE
"Enable push notifications" is active on devices without FCM support

### ISSUE THREAD

**Issue by gdt** [BelledonneCommunications/linphone-android#544] opened 2019-04-02 19:16 UTC
Linphone 4.0.1 from f-droid, LineageOS 15.1 (AOSP 8.1.0), with no GAPPS.

In a sip account, there is "Allow push notifications".  Under Network (not per account), there is "Enable push notifications".  Separately from this being confusing (presumably globally enabled or not, and then per account whether to send a token at registration time), I find that neither is greyed out, and both can be checked.  Surely this cannot be working, as my device has no FCM client code (which is a choice made by some and not others, not a bug).

To fix, grey out the push menu items if the API is not actually available.
Further, if the global "Enable" setting is disabled, grey out the per-account "Allow" setting.

**Comment by licaon-kter** [comment] 2019-04-02 19:19
/duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/482

**Comment by Viish** [comment] 2019-04-03 07:37
@gdt Do you know an API that would allow to know if the device supports FCM ?

@licaon-kter Currently there is no option to make it disappear automatically

**Comment by gdt** [comment] 2019-04-03 13:59
There's another nuance, which is that there are even more flavors of devices:
 - ROMS with native gapps (most stock).  Perhaps ROMS with gapps added are similar.
 - ROMS with microg, with FCM enabled.
 - ROMS with microg, with FCM disabled.
 - ROMS without gapps and without microg.

So I think there needs to be compile time checking if the headers/code isn't there, and then at runtime if registration fails with no supported, go to grey mode.   I see there's progress on the other ticket.

**Comment by Viish** [comment] 2019-04-03 14:00
What's microg ? Except for that, it should be ok now.

**Closed** 2019-04-03 14:04 UTC

**Comment by gdt** [comment] 2019-04-03 14:06
In addition to what you found about microg, note that there is https://lineage.microg.org/ which is a build of lineage with microg built in.  This lets people use alternative location providers, and to enable FCM if they want, and not enable it if they don't want.  This is really just the case "ROMS with microg", but it's the easy way to end up with a system with microg.

**Comment by licaon-kter** [comment] 2019-04-03 14:45
@gdt keep in mind that you'll need the app from Google Play store for it to have working push.

**Comment by gdt** [comment] 2019-04-03 14:50
Thanks, I do understand that, but I intentionally have a system without FCM or other gapps, and I get my apps from f-droid (thank you for your efforts).  I am not wanting push to work, at least until it can be done with open protocols and not a centralized server.  I was just reporting a bug that it was offered when it shouldn't be.
